// Mocks generated by Mockito 5.4.6 from annotations
// in versus_space/test/features/profile/domain/usecases/profile/watch_user_profile_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:versus_space/features/profile/domain/models/user_profile.dart'
    as _i4;
import 'package:versus_space/features/profile/domain/models/user_settings.dart'
    as _i5;
import 'package:versus_space/features/profile/domain/repositories/i_user_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUserRepository extends _i1.Mock implements _i2.IUserRepository {
  MockIUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.UserProfile?> getUserByUid(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByUid, [uid]),
            returnValue: _i3.Future<_i4.UserProfile?>.value(),
          )
          as _i3.Future<_i4.UserProfile?>);

  @override
  _i3.Future<_i4.UserProfile?> getUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i3.Future<_i4.UserProfile?>.value(),
          )
          as _i3.Future<_i4.UserProfile?>);

  @override
  _i3.Stream<_i4.UserProfile?> watchUserProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchUserProfile, [userId]),
            returnValue: _i3.Stream<_i4.UserProfile?>.empty(),
          )
          as _i3.Stream<_i4.UserProfile?>);

  @override
  _i3.Future<void> createUser(_i4.UserProfile? user) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateUser(String? uid, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [uid, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateUserProfile(_i4.UserProfile? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [uid]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> userExists(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#userExists, [uid]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i5.UserSettings?> getUserSettings(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserSettings, [uid]),
            returnValue: _i3.Future<_i5.UserSettings?>.value(),
          )
          as _i3.Future<_i5.UserSettings?>);

  @override
  _i3.Future<void> updateUserSettings(
    String? userId,
    Map<String, dynamic>? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserSettings, [userId, settings]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.UserProfile?> getCurrentUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserProfile, []),
            returnValue: _i3.Future<_i4.UserProfile?>.value(),
          )
          as _i3.Future<_i4.UserProfile?>);

  @override
  _i3.Future<void> updateCurrentUserProfile(_i4.UserProfile? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateCurrentUserProfile, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
