// Password Management UseCase
// Clean Architecture - Domain Layer

import 'package:fpdart/fpdart.dart';
import 'package:flutter/foundation.dart';
import '/core/utils/idempotency_service.dart';
import '../../repositories/i_auth_repository.dart';
import '../../failures/auth_failure.dart';

/// PasswordManagementUseCase
///
/// Comprehensive password management that handles:
/// - Password reset via email with spam prevention
/// - Password updates for authenticated users
/// - Password strength validation
///
/// **Clean Architecture v4.0 - Either Pattern + IdempotencyService**:
/// - Returns Either<AuthFailure, Unit> for functional error handling
/// - IdempotencyService integration for attack prevention
/// - Consistent with Voting feature architecture
class PasswordManagementUseCase {
  final IAuthRepository _repository;
  final IdempotencyService _idempotencyService;

  PasswordManagementUseCase({
    required IAuthRepository repository,
    required IdempotencyService idempotencyService,
  })  : _repository = repository,
        _idempotencyService = idempotencyService;

  /// Send Password Reset Email with Idempotency
  ///
  /// Uses IdempotencyService to prevent spam attacks:
  /// - First execution: Sends email and stores eventId
  /// - Network retry (same eventId): Skips operation safely
  /// - Attack attempt (different eventId): Returns success without sending (already sent)
  ///
  /// [email] - Email address to send password reset to
  /// [eventId] - UUID v4 generated by client for idempotency check
  ///
  /// Returns Either<AuthFailure, Unit> with automatic Korean error messages
  Future<Either<AuthFailure, Unit>> sendPasswordResetEmail({
    required String email,
    required String eventId,
  }) async {
    try {
      debugPrint('Sending password reset email to: $email (eventId: $eventId)');

      // 1. Validate email format (Business Logic)
      if (!_isValidEmail(email)) {
        debugPrint('Invalid email format: $email');
        return left(const AuthFailure.invalidEmail());
      }

      // 2. Execute with IdempotencyService
      await _idempotencyService.executeIdempotent<void>(
        entityType: 'auth_password_reset',
        entityId: email,
        userId: email,
        eventId: eventId,
        operation: (transaction) async {
          debugPrint('Idempotency check passed, sending password reset email...');

          // Send reset email (Repository returns Either)
          final resetResult = await _repository.sendPasswordResetEmail(email);
          resetResult.fold(
            (failure) {
              debugPrint('Failed to send password reset email');
              throw failure;
            },
            (_) {
              debugPrint('Password reset email sent successfully');
            },
          );
        },
      );

      return right(unit);

    } on IdempotencyViolation catch (e) {
      // Already sent - treat as success to prevent attack feedback
      debugPrint('Password reset email already sent (attack prevention): $e');
      return right(unit);
    } on AuthFailure catch (e) {
      debugPrint('Password reset failed with AuthFailure: ${e.message}');
      return left(e);
    } catch (e) {
      debugPrint('Password reset failed with unexpected error: $e');
      return left(AuthFailure.unexpected(e.toString()));
    }
  }

  /// Update Password
  ///
  /// Updates the password for the currently authenticated user
  ///
  /// Returns Either<AuthFailure, Unit> with automatic Korean error messages
  Future<Either<AuthFailure, Unit>> updatePassword({
    required String currentPassword,
    required String newPassword,
  }) async {
    debugPrint('Updating user password...');

    // 1. Validate new password strength (Business Logic)
    if (!_isValidPassword(newPassword)) {
      debugPrint('New password does not meet requirements');
      return left(const AuthFailure.weakPassword());
    }

    // 2. Verify passwords are different (Business Logic)
    if (currentPassword == newPassword) {
      debugPrint('New password must be different from current password');
      return left(AuthFailure.unexpected('새 비밀번호는 현재 비밀번호와 달라야 합니다'));
    }

    // 3. Check if user is authenticated (Business Logic)
    if (!_repository.isSignedIn) {
      debugPrint('User must be authenticated to update password');
      return left(const AuthFailure.userNotFound());
    }

    // 4. Get current user (Repository returns Either)
    final userResult = await _repository.getCurrentUser();
    final currentUser = userResult.fold(
      (failure) {
        debugPrint('Could not get current user details');
        return null;
      },
      (user) => user,
    );

    if (currentUser == null || currentUser.email == null) {
      debugPrint('Could not get current user email');
      return left(const AuthFailure.userNotFound());
    }

    // 5. Re-authenticate to verify current password (Repository returns Either)
    final reAuthResult = await _repository.signInWithEmailAndPassword(
      currentUser.email!,
      currentPassword,
    );

    final reAuthSuccess = reAuthResult.fold(
      (failure) {
        debugPrint('Current password is incorrect: ${failure.message}');
        return false;
      },
      (_) => true,
    );

    if (!reAuthSuccess) {
      return left(const AuthFailure.invalidCredentials());
    }

    // 6. Update to new password (Repository returns Either<AuthFailure, bool>)
    final updateResult = await _repository.updatePassword(newPassword);

    return updateResult.fold(
      (failure) {
        debugPrint('Password update failed with AuthFailure: ${failure.message}');
        return left(failure);
      },
      (_) {
        debugPrint('Password updated successfully');
        return right(unit);
      },
    );
  }

  /// Reset Password (Backward compatibility)
  ///
  /// Alias for sendPasswordResetEmail
  ///
  /// [email] - Email address to send password reset to
  /// [eventId] - UUID v4 generated by client for idempotency check
  ///
  /// Returns Either<AuthFailure, Unit> with automatic Korean error messages
  Future<Either<AuthFailure, Unit>> resetPassword({
    required String email,
    required String eventId,
  }) async {
    return sendPasswordResetEmail(email: email, eventId: eventId);
  }

  /// Validate email format
  bool _isValidEmail(String email) {
    final emailRegex = RegExp(
      r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$',
    );
    return emailRegex.hasMatch(email);
  }

  /// Validate password strength
  bool _isValidPassword(String password) {
    // Minimum 6 characters (Firebase requirement)
    if (password.length < 6) {
      return false;
    }

    // Additional requirements could be added:
    // - Contains uppercase letter
    // - Contains lowercase letter
    // - Contains number
    // - Contains special character

    return true;
  }

  /// Check password strength
  ///
  /// Returns a score from 0 to 100 indicating password strength
  int getPasswordStrength(String password) {
    int score = 0;

    // Length scoring
    if (password.length >= 6) score += 20;
    if (password.length >= 8) score += 20;
    if (password.length >= 12) score += 20;

    // Character variety scoring
    if (RegExp(r'[a-z]').hasMatch(password)) score += 10;
    if (RegExp(r'[A-Z]').hasMatch(password)) score += 10;
    if (RegExp(r'[0-9]').hasMatch(password)) score += 10;
    if (RegExp(r'[!@#$%^&*(),.?":{}|<>]').hasMatch(password)) score += 10;

    return score.clamp(0, 100);
  }
}
