// Mocks generated by Mockito 5.4.6 from annotations
// in versus_space/test/widgets/profile_page_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:versus_space/features/posts/domain/models/post.dart' as _i7;
import 'package:versus_space/features/posts/domain/models/vote_data.dart'
    as _i9;
import 'package:versus_space/features/posts/domain/repositories/i_post_repository.dart'
    as _i6;
import 'package:versus_space/features/profile/domain/models/user_profile.dart'
    as _i3;
import 'package:versus_space/features/profile/domain/repositories/i_user_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCollectionReference_0<T extends Object?> extends _i1.SmartFake
    implements _i2.CollectionReference<T> {
  _FakeCollectionReference_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfile_1 extends _i1.SmartFake implements _i3.UserProfile {
  _FakeUserProfile_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentReference_2<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T> {
  _FakeDocumentReference_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseFirestore_3 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentSnapshot_4<T1 extends Object?> extends _i1.SmartFake
    implements _i2.DocumentSnapshot<T1> {
  _FakeDocumentSnapshot_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUserRepository extends _i1.Mock implements _i4.IUserRepository {
  MockIUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CollectionReference<Object?> get usersCollection => (super.noSuchMethod(
        Invocation.getter(#usersCollection),
        returnValue: _FakeCollectionReference_0<Object?>(
          this,
          Invocation.getter(#usersCollection),
        ),
      ) as _i2.CollectionReference<Object?>);

  @override
  _i5.Stream<_i3.UserProfile> getUserStream(
          _i2.DocumentReference<Object?>? ref) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserStream,
          [ref],
        ),
        returnValue: _i5.Stream<_i3.UserProfile>.empty(),
      ) as _i5.Stream<_i3.UserProfile>);

  @override
  _i5.Future<_i3.UserProfile> getUserOnce(
          _i2.DocumentReference<Object?>? ref) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserOnce,
          [ref],
        ),
        returnValue: _i5.Future<_i3.UserProfile>.value(_FakeUserProfile_1(
          this,
          Invocation.method(
            #getUserOnce,
            [ref],
          ),
        )),
      ) as _i5.Future<_i3.UserProfile>);

  @override
  _i5.Future<_i3.UserProfile?> getUserByUid(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #getUserByUid,
          [uid],
        ),
        returnValue: _i5.Future<_i3.UserProfile?>.value(),
      ) as _i5.Future<_i3.UserProfile?>);

  @override
  _i5.Stream<_i3.UserProfile?> getUserStreamByUid(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserStreamByUid,
          [uid],
        ),
        returnValue: _i5.Stream<_i3.UserProfile?>.empty(),
      ) as _i5.Stream<_i3.UserProfile?>);

  @override
  _i5.Future<void> createUser(_i3.UserProfile? user) => (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [user],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateUser(
    String? uid,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [
            uid,
            data,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateUserProfile(_i3.UserProfile? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [user],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteUser(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [uid],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.UserProfile>> searchUsersByName(
    String? query, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUsersByName,
          [query],
          {#limit: limit},
        ),
        returnValue:
            _i5.Future<List<_i3.UserProfile>>.value(<_i3.UserProfile>[]),
      ) as _i5.Future<List<_i3.UserProfile>>);

  @override
  _i5.Future<List<_i3.UserProfile>> getUserFriends(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserFriends,
          [uid],
        ),
        returnValue:
            _i5.Future<List<_i3.UserProfile>>.value(<_i3.UserProfile>[]),
      ) as _i5.Future<List<_i3.UserProfile>>);

  @override
  _i5.Future<List<_i3.UserProfile>> getUsersByIds(List<String>? uids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsersByIds,
          [uids],
        ),
        returnValue:
            _i5.Future<List<_i3.UserProfile>>.value(<_i3.UserProfile>[]),
      ) as _i5.Future<List<_i3.UserProfile>>);

  @override
  _i5.Future<void> updateUserPoints(
    String? uid,
    int? pointsA,
    int? pointsQ,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPoints,
          [
            uid,
            pointsA,
            pointsQ,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateUserRanking(
    String? uid,
    String? rank,
    String? title,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserRanking,
          [
            uid,
            rank,
            title,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> getUsersCount(
          {_i2.Query<Object?> Function(_i2.Query<Object?>)? queryBuilder}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsersCount,
          [],
          {#queryBuilder: queryBuilder},
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Stream<List<_i3.UserProfile>> queryUsers({
    _i2.Query<Object?> Function(_i2.Query<Object?>)? queryBuilder,
    int? limit = -1,
    bool? singleRecord = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryUsers,
          [],
          {
            #queryBuilder: queryBuilder,
            #limit: limit,
            #singleRecord: singleRecord,
          },
        ),
        returnValue: _i5.Stream<List<_i3.UserProfile>>.empty(),
      ) as _i5.Stream<List<_i3.UserProfile>>);

  @override
  _i5.Future<List<_i3.UserProfile>> queryUsersOnce({
    _i2.Query<Object?> Function(_i2.Query<Object?>)? queryBuilder,
    int? limit = -1,
    bool? singleRecord = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryUsersOnce,
          [],
          {
            #queryBuilder: queryBuilder,
            #limit: limit,
            #singleRecord: singleRecord,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.UserProfile>>.value(<_i3.UserProfile>[]),
      ) as _i5.Future<List<_i3.UserProfile>>);

  @override
  _i5.Future<bool> userExists(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #userExists,
          [uid],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i2.DocumentReference<Object?> getUserReference(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserReference,
          [uid],
        ),
        returnValue: _FakeDocumentReference_2<Object?>(
          this,
          Invocation.method(
            #getUserReference,
            [uid],
          ),
        ),
      ) as _i2.DocumentReference<Object?>);
}

/// A class which mocks [IPostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPostRepository extends _i1.Mock implements _i6.IPostRepository {
  MockIPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i7.Post>> getAllPosts() => (super.noSuchMethod(
        Invocation.method(
          #getAllPosts,
          [],
        ),
        returnValue: _i5.Stream<List<_i7.Post>>.empty(),
      ) as _i5.Stream<List<_i7.Post>>);

  @override
  _i5.Stream<List<_i7.Post>> getPostsByUserId(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPostsByUserId,
          [userId],
        ),
        returnValue: _i5.Stream<List<_i7.Post>>.empty(),
      ) as _i5.Stream<List<_i7.Post>>);

  @override
  _i5.Future<_i7.Post?> getPostById(String? postId) => (super.noSuchMethod(
        Invocation.method(
          #getPostById,
          [postId],
        ),
        returnValue: _i5.Future<_i7.Post?>.value(),
      ) as _i5.Future<_i7.Post?>);

  @override
  _i5.Stream<_i7.Post?> getPostStream(String? postId) => (super.noSuchMethod(
        Invocation.method(
          #getPostStream,
          [postId],
        ),
        returnValue: _i5.Stream<_i7.Post?>.empty(),
      ) as _i5.Stream<_i7.Post?>);

  @override
  _i5.Future<String> createPost(_i7.Post? post) => (super.noSuchMethod(
        Invocation.method(
          #createPost,
          [post],
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createPost,
            [post],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> updatePost(
    String? postId,
    _i7.Post? post,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePost,
          [
            postId,
            post,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deletePost(String? postId) => (super.noSuchMethod(
        Invocation.method(
          #deletePost,
          [postId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateVoteData(
    String? postId,
    _i9.VoteData? voteData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVoteData,
          [
            postId,
            voteData,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> castVote(
    String? postId,
    String? userId,
    String? option,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #castVote,
          [
            postId,
            userId,
            option,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeVote(
    String? postId,
    String? userId,
    String? option,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeVote,
          [
            postId,
            userId,
            option,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<List<_i7.Post>> getPostsByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPostsByCategory,
          [category],
        ),
        returnValue: _i5.Stream<List<_i7.Post>>.empty(),
      ) as _i5.Stream<List<_i7.Post>>);

  @override
  _i5.Stream<List<_i7.Post>> getPostsByTags(List<String>? tags) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPostsByTags,
          [tags],
        ),
        returnValue: _i5.Stream<List<_i7.Post>>.empty(),
      ) as _i5.Stream<List<_i7.Post>>);

  @override
  _i5.Stream<List<_i7.Post>> getTrendingPosts({int? limit = 20}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrendingPosts,
          [],
          {#limit: limit},
        ),
        returnValue: _i5.Stream<List<_i7.Post>>.empty(),
      ) as _i5.Stream<List<_i7.Post>>);

  @override
  _i5.Stream<List<_i7.Post>> getRecentPosts({int? limit = 20}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentPosts,
          [],
          {#limit: limit},
        ),
        returnValue: _i5.Stream<List<_i7.Post>>.empty(),
      ) as _i5.Stream<List<_i7.Post>>);

  @override
  _i5.Stream<List<_i7.Post>> searchPosts(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchPosts,
          [query],
        ),
        returnValue: _i5.Stream<List<_i7.Post>>.empty(),
      ) as _i5.Stream<List<_i7.Post>>);

  @override
  _i5.Future<List<_i7.Post>> getPostsPaginated({
    _i2.DocumentSnapshot<Object?>? lastDocument,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPostsPaginated,
          [],
          {
            #lastDocument: lastDocument,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<List<_i7.Post>>.value(<_i7.Post>[]),
      ) as _i5.Future<List<_i7.Post>>);

  @override
  _i5.Future<void> reportPost(
    String? postId,
    String? userId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportPost,
          [
            postId,
            userId,
            reason,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updatePostStats(
    String? postId,
    Map<String, dynamic>? stats,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePostStats,
          [
            postId,
            stats,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<List<_i7.Post>> getPostsByVisibility(int? visibility) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPostsByVisibility,
          [visibility],
        ),
        returnValue: _i5.Stream<List<_i7.Post>>.empty(),
      ) as _i5.Stream<List<_i7.Post>>);

  @override
  _i5.Stream<List<_i7.Post>> getAnonymousPosts() => (super.noSuchMethod(
        Invocation.method(
          #getAnonymousPosts,
          [],
        ),
        returnValue: _i5.Stream<List<_i7.Post>>.empty(),
      ) as _i5.Stream<List<_i7.Post>>);

  @override
  _i5.Stream<List<_i7.Post>> getPremiumPosts() => (super.noSuchMethod(
        Invocation.method(
          #getPremiumPosts,
          [],
        ),
        returnValue: _i5.Stream<List<_i7.Post>>.empty(),
      ) as _i5.Stream<List<_i7.Post>>);

  @override
  _i5.Future<void> completeVote(String? postId) => (super.noSuchMethod(
        Invocation.method(
          #completeVote,
          [postId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelVote(
    String? postId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelVote,
          [
            postId,
            reason,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> sendNotifications(String? postId) => (super.noSuchMethod(
        Invocation.method(
          #sendNotifications,
          [postId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> getVoteResults(String? postId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVoteResults,
          [postId],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<bool> hasUserVoted(
    String? postId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasUserVoted,
          [
            postId,
            userId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<String?> getUserVoteOption(
    String? postId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserVoteOption,
          [
            postId,
            userId,
          ],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);
}

/// A class which mocks [DocumentReference].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockDocumentReference<T extends Object?> extends _i1.Mock
    implements _i2.DocumentReference<T> {
  MockDocumentReference() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseFirestore get firestore => (super.noSuchMethod(
        Invocation.getter(#firestore),
        returnValue: _FakeFirebaseFirestore_3(
          this,
          Invocation.getter(#firestore),
        ),
      ) as _i2.FirebaseFirestore);

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  _i2.CollectionReference<T> get parent => (super.noSuchMethod(
        Invocation.getter(#parent),
        returnValue: _FakeCollectionReference_0<T>(
          this,
          Invocation.getter(#parent),
        ),
      ) as _i2.CollectionReference<T>);

  @override
  String get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
      ) as String);

  @override
  _i2.CollectionReference<Map<String, dynamic>> collection(
          String? collectionPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #collection,
          [collectionPath],
        ),
        returnValue: _FakeCollectionReference_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #collection,
            [collectionPath],
          ),
        ),
      ) as _i2.CollectionReference<Map<String, dynamic>>);

  @override
  _i5.Future<void> delete() => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> update(Map<Object, Object?>? data) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [data],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.DocumentSnapshot<T>> get([_i2.GetOptions? options]) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [options],
        ),
        returnValue: _i5.Future<_i2.DocumentSnapshot<T>>.value(
            _FakeDocumentSnapshot_4<T>(
          this,
          Invocation.method(
            #get,
            [options],
          ),
        )),
      ) as _i5.Future<_i2.DocumentSnapshot<T>>);

  @override
  _i5.Stream<_i2.DocumentSnapshot<T>> snapshots({
    bool? includeMetadataChanges = false,
    _i2.ListenSource? source = _i2.ListenSource.defaultSource,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #snapshots,
          [],
          {
            #includeMetadataChanges: includeMetadataChanges,
            #source: source,
          },
        ),
        returnValue: _i5.Stream<_i2.DocumentSnapshot<T>>.empty(),
      ) as _i5.Stream<_i2.DocumentSnapshot<T>>);

  @override
  _i5.Future<void> set(
    T? data, [
    _i2.SetOptions? options,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #set,
          [
            data,
            options,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i2.DocumentReference<R> withConverter<R>({
    required _i2.FromFirestore<R>? fromFirestore,
    required _i2.ToFirestore<R>? toFirestore,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #withConverter,
          [],
          {
            #fromFirestore: fromFirestore,
            #toFirestore: toFirestore,
          },
        ),
        returnValue: _FakeDocumentReference_2<R>(
          this,
          Invocation.method(
            #withConverter,
            [],
            {
              #fromFirestore: fromFirestore,
              #toFirestore: toFirestore,
            },
          ),
        ),
      ) as _i2.DocumentReference<R>);
}
