// Mocks generated by Mockito 5.4.6 from annotations
// in versus_space/test/features/profile/presentation/providers/profile_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i10;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:versus_space/features/profile/domain/failures/profile_failures.dart'
    as _i5;
import 'package:versus_space/features/profile/domain/models/user_profile.dart'
    as _i6;
import 'package:versus_space/features/profile/domain/usecases/profile/get_current_user_profile_usecase.dart'
    as _i7;
import 'package:versus_space/features/profile/domain/usecases/profile/get_profile_completion_usecase.dart'
    as _i11;
import 'package:versus_space/features/profile/domain/usecases/profile/get_user_profile_usecase.dart'
    as _i3;
import 'package:versus_space/features/profile/domain/usecases/profile/update_user_profile_usecase.dart'
    as _i8;
import 'package:versus_space/features/profile/domain/usecases/profile/upload_profile_image_usecase.dart'
    as _i9;
import 'package:versus_space/features/profile/domain/usecases/profile/watch_user_profile_usecase.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetUserProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserProfileUseCase extends _i1.Mock
    implements _i3.GetUserProfileUseCase {
  MockGetUserProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ProfileFailure, _i6.UserProfile>> execute({
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {#userId: userId}),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.ProfileFailure, _i6.UserProfile>
                >.value(
                  _FakeEither_0<_i5.ProfileFailure, _i6.UserProfile>(
                    this,
                    Invocation.method(#execute, [], {#userId: userId}),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.ProfileFailure, _i6.UserProfile>>);
}

/// A class which mocks [GetCurrentUserProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentUserProfileUseCase extends _i1.Mock
    implements _i7.GetCurrentUserProfileUseCase {
  MockGetCurrentUserProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ProfileFailure, _i6.UserProfile>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.ProfileFailure, _i6.UserProfile>
                >.value(
                  _FakeEither_0<_i5.ProfileFailure, _i6.UserProfile>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.ProfileFailure, _i6.UserProfile>>);
}

/// A class which mocks [UpdateUserProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUserProfileUseCase extends _i1.Mock
    implements _i8.UpdateUserProfileUseCase {
  MockUpdateUserProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ProfileFailure, void>> execute(
    _i6.UserProfile? profile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [profile]),
            returnValue: _i4.Future<_i2.Either<_i5.ProfileFailure, void>>.value(
              _FakeEither_0<_i5.ProfileFailure, void>(
                this,
                Invocation.method(#execute, [profile]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.ProfileFailure, void>>);
}

/// A class which mocks [UploadProfileImageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadProfileImageUseCase extends _i1.Mock
    implements _i9.UploadProfileImageUseCase {
  MockUploadProfileImageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ProfileFailure, String>> execute({
    required String? userId,
    required _i10.File? imageFile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #userId: userId,
              #imageFile: imageFile,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.ProfileFailure, String>>.value(
                  _FakeEither_0<_i5.ProfileFailure, String>(
                    this,
                    Invocation.method(#execute, [], {
                      #userId: userId,
                      #imageFile: imageFile,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.ProfileFailure, String>>);
}

/// A class which mocks [GetProfileCompletionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileCompletionUseCase extends _i1.Mock
    implements _i11.GetProfileCompletionUseCase {
  MockGetProfileCompletionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ProfileFailure, double>> execute(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [userId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.ProfileFailure, double>>.value(
                  _FakeEither_0<_i5.ProfileFailure, double>(
                    this,
                    Invocation.method(#execute, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.ProfileFailure, double>>);
}

/// A class which mocks [WatchUserProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchUserProfileUseCase extends _i1.Mock
    implements _i12.WatchUserProfileUseCase {
  MockWatchUserProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.Either<_i5.ProfileFailure, _i6.UserProfile>> execute({
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {#userId: userId}),
            returnValue:
                _i4.Stream<
                  _i2.Either<_i5.ProfileFailure, _i6.UserProfile>
                >.empty(),
          )
          as _i4.Stream<_i2.Either<_i5.ProfileFailure, _i6.UserProfile>>);
}
