import 'package:freezed_annotation/freezed_annotation.dart';
import '/app/contracts/notification_types.dart';
import 'vote_options.dart';

part 'vote_notification.freezed.dart';
part 'vote_notification.g.dart';

/// 투표 알림 도메인 모델
/// Clean Architecture - Voting Feature의 독립 도메인 엔티티
///
/// **Freezed Migration**: Plain class → Freezed로 변환 (2025-01-25)
/// - 불변성 자동 보장
/// - copyWith/JSON 자동 생성
/// - 76줄 boilerplate 제거
/// - 11개 비즈니스 로직 유지
///
/// Note: Notification.voting()과는 별개의 타입
/// - VoteNotification: Voting Feature의 비즈니스 로직 담당
/// - Notification.voting(): Notifications Feature의 데이터 전송 타입
@freezed
sealed class VoteNotification with _$VoteNotification {
  const VoteNotification._();  // Private constructor for custom getters

  // ===== TYPE 상수 정의 (Contract 참조) =====
  static const String TYPE = NotificationTypes.votingRequest;

  const factory VoteNotification({
    // ===== 공통 알림 필드 (Notification에서 가져옴) =====
    required String id,
    required String userId,
    required DateTime createdAt,
    required bool isRead,
    required String title,
    required String content,
    DateTime? readAt,
    DateTime? expiryTime,
    @Default({}) Map<String, dynamic> metadata,

    // ===== 투표 전용 필드 =====
    required String postId,
    required String postTitle,
    required String postContent,
    String? postDescription,
    required VoteOptions voteOptions,
    required DateTime voteStartTime,
    required DateTime voteEndTime,
    String? targetAudience,
    int? currentVotesA,
    int? currentVotesB,
    @Default(false) bool hasVoted,
    String? userVoteChoice,
    String? senderId,
    String? senderName,
    String? body,
    @JsonKey(
      fromJson: NotificationPriority.fromJson,
      toJson: _notificationPriorityToJson,
    )
    @Default(NotificationPriority.medium)
    NotificationPriority notificationPriority,
  }) = _VoteNotification;

  factory VoteNotification.fromJson(Map<String, dynamic> json) =>
      _$VoteNotificationFromJson(json);

  // ============================================================================
  // 공통 알림 비즈니스 로직
  // ============================================================================

  /// 알림이 만료되었는지 확인
  bool get isExpired {
    if (expiryTime == null) return false;
    return DateTime.now().isAfter(expiryTime!);
  }

  /// 투표 알림의 우선순위 계산 (Voting Feature 책임)
  int get priority {
    // 투표 요청이면서 읽지 않은 경우 가장 높은 우선순위
    if (!isRead && !isExpired) {
      return 3;
    }
    // 기본 우선순위 (읽은 알림)
    return 0;
  }

  // ============================================================================
  // 투표 관련 비즈니스 로직
  // ============================================================================

  /// 투표가 활성 상태인지 확인
  bool get isVoteActive {
    final now = DateTime.now();
    return now.isAfter(voteStartTime) && now.isBefore(voteEndTime);
  }

  /// 투표가 종료되었는지 확인
  bool get isVoteEnded {
    return DateTime.now().isAfter(voteEndTime);
  }

  /// 투표가 아직 시작되지 않았는지 확인
  bool get isVotePending {
    return DateTime.now().isBefore(voteStartTime);
  }

  /// 남은 투표 시간
  Duration? get remainingTime {
    if (isVoteEnded) return null;
    if (isVotePending) return voteEndTime.difference(voteStartTime);
    return voteEndTime.difference(DateTime.now());
  }

  /// 전체 투표 기간
  Duration get totalVotingDuration {
    return voteEndTime.difference(voteStartTime);
  }

  /// 투표 진행률 (퍼센트)
  double get completionPercentage {
    if (isVotePending) return 0.0;
    if (isVoteEnded) return 100.0;

    final elapsed = DateTime.now().difference(voteStartTime);
    final total = totalVotingDuration;
    if (total.inSeconds == 0) return 0.0;

    return (elapsed.inSeconds / total.inSeconds * 100).clamp(0.0, 100.0);
  }

  /// 사용자가 투표할 수 있는지 확인 (알림 UI 표시용)
  /// Note: 실제 투표 로직은 Voting Feature에서 처리
  bool get canUserVote {
    return isVoteActive && !hasVoted && !isExpired;
  }

  /// 투표 상태 문자열
  String get voteStatus {
    if (isVotePending) return 'pending';
    if (isVoteActive) return 'active';
    if (isVoteEnded) return 'ended';
    return 'unknown';
  }

  /// 남은 시간 포맷팅
  String get formattedRemainingTime {
    final remaining = remainingTime;
    if (remaining == null) return '종료됨';

    if (remaining.inDays > 0) {
      return '${remaining.inDays}일 ${remaining.inHours % 24}시간';
    } else if (remaining.inHours > 0) {
      return '${remaining.inHours}시간 ${remaining.inMinutes % 60}분';
    } else if (remaining.inMinutes > 0) {
      return '${remaining.inMinutes}분 ${remaining.inSeconds % 60}초';
    } else {
      return '${remaining.inSeconds}초';
    }
  }

  // ============================================================================
  // Freezed Migration Notes
  // ============================================================================
  //
  // Removed methods (now auto-generated by Freezed):
  // - copyWith() - 54 lines → Freezed auto-generates
  // - markAsRead() - 22 lines → Use: notification.copyWith(isRead: true, readAt: DateTime.now())
  //
  // Usage example:
  // ```dart
  // // Before (manual copyWith)
  // final updated = notification.copyWith(isRead: true);
  //
  // // After (Freezed auto-generated)
  // final updated = notification.copyWith(isRead: true);  // Same API!
  //
  // // markAsRead replacement
  // final read = notification.copyWith(
  //   isRead: true,
  //   readAt: DateTime.now(),
  // );
  // ```
}

// JSON serialization helper for NotificationPriority
int _notificationPriorityToJson(NotificationPriority priority) => priority.toJson();
