import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'ko', 'zh_Hans', 'ja', 'es', 'fr', 'hi', 'id', 'it'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? koText = '',
    String? zh_HansText = '',
    String? jaText = '',
    String? esText = '',
    String? frText = '',
    String? hiText = '',
    String? idText = '',
    String? itText = '',
  }) =>
      [
        enText,
        koText,
        zh_HansText,
        jaText,
        esText,
        frText,
        hiText,
        idText,
        itText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

/// Used if the locale is not supported by GlobalMaterialLocalizations.
class FallbackMaterialLocalizationDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const FallbackMaterialLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<MaterialLocalizations> load(Locale locale) async =>
      SynchronousFuture<MaterialLocalizations>(
        const DefaultMaterialLocalizations(),
      );

  @override
  bool shouldReload(FallbackMaterialLocalizationDelegate old) => false;
}

/// Used if the locale is not supported by GlobalCupertinoLocalizations.
class FallbackCupertinoLocalizationDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const FallbackCupertinoLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      SynchronousFuture<CupertinoLocalizations>(
        const DefaultCupertinoLocalizations(),
      );

  @override
  bool shouldReload(FallbackCupertinoLocalizationDelegate old) => false;
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

bool _isSupportedLocale(Locale locale) {
  final language = locale.toString();
  return FFLocalizations.languages().contains(
    language.endsWith('_')
        ? language.substring(0, language.length - 1)
        : language,
  );
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // Login_page
  {
    'b6l0k8k2': {
      'en': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'hi': 'ईमेल',
      'id': 'E-mail',
      'it': 'E-mail',
      'ja': 'メール',
      'ko': '이메일',
      'zh_Hans': '电子邮件',
    },
    '6l9ekgal': {
      'en': 'Password',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'hi': 'पासवर्ड',
      'id': 'Kata sandi',
      'it': 'Password',
      'ja': 'パスワード',
      'ko': '비밀번호',
      'zh_Hans': '密码',
    },
    '4wwn8ov8': {
      'en': 'Log in',
      'es': 'acceso',
      'fr': 'se connecter',
      'hi': 'लॉग इन करें',
      'id': 'Masuk',
      'it': 'login',
      'ja': 'ログイン',
      'ko': '로그인하다',
      'zh_Hans': '登录',
    },
    'uk1cwrhu': {
      'en': 'Phone Log in',
      'es': 'acceso',
      'fr': 'se connecter',
      'hi': 'लॉग इन करें',
      'id': 'Masuk',
      'it': 'login',
      'ja': 'ログイン',
      'ko': '로그인하다',
      'zh_Hans': '登录',
    },
    'ymtbo8l4': {
      'en': 'Forgot Password',
      'es': 'Has olvidado tu contraseña',
      'fr': 'Mot de passe oublié',
      'hi': 'पासवर्ड भूल गए',
      'id': 'Lupa Kata Sandi',
      'it': 'Ha dimenticato la password',
      'ja': 'パスワードをお忘れですか',
      'ko': '비밀번호를 잊으셨나요?',
      'zh_Hans': '忘记密码',
    },
    'e1wsx5w1': {
      'en': 'Or sign up with, goto test',
      'es': 'O regístrate con',
      'fr': 'Ou inscrivez-vous avec',
      'hi': 'या साइन अप करें',
      'id': 'Atau daftar dengan',
      'it': 'Oppure registrati con',
      'ja': 'またはサインアップ',
      'ko': '또는 가입하세요',
      'zh_Hans': '或注册',
    },
    'zodqb7tr': {
      'en': 'Please enter a valid email address.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'j0tjwsb0': {
      'en': 'Please choose an option from the dropdown',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'a3s2kg05': {
      'en': 'Password must be at least 6 characters',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'h1k710sg': {
      'en': 'Please choose an option from the dropdown',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '293kt2nw': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'zh_Hans': '家',
    },
  },
  // Create_Account
  {
    'hkdfn0nl': {
      'en': 'Welcome to\n           Versus Space',
      'es': 'Bienvenidos a\n\nVersus Space',
      'fr': 'Bienvenue à\n\nVersus Space',
      'hi': 'आपका स्वागत है\n\nवर्सेस स्पेस',
      'id': 'Selamat datang di\n\nVersus Space',
      'it': 'Benvenuti a\n\nVersus Space',
      'ja': 'ようこそ\n\nVersus Space',
      'ko': '\n\nVersus Space에 오신 것을 환영합니다.',
      'zh_Hans': '欢迎来到\n\nVersus Space',
    },
    'r6bw196y': {
      'en': 'Create an account',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'hi': 'खाता बनाएं',
      'id': 'Buat akun',
      'it': 'Creare un account',
      'ja': 'アカウントを作成する',
      'ko': '계정을 생성하세요',
      'zh_Hans': '创建一个帐户',
    },
    'vyjbjx7u': {
      'en': 'Let\'s get started by filling out the form below.',
      'es': 'Comencemos llenando el formulario a continuación.',
      'fr': 'Commençons par remplir le formulaire ci-dessous.',
      'hi': 'आइये नीचे दिया गया फॉर्म भरकर शुरुआत करें।',
      'id': 'Mari kita mulai dengan mengisi formulir di bawah ini.',
      'it': 'Iniziamo compilando il modulo sottostante.',
      'ja': 'まずは以下のフォームに記入しましょう。',
      'ko': '아래 양식을 작성하여 시작해 보겠습니다.',
      'zh_Hans': '让我们从填写下面的表格开始。',
    },
    'b4wuzum8': {
      'en': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'hi': 'ईमेल',
      'id': 'E-mail',
      'it': 'E-mail',
      'ja': 'メール',
      'ko': '이메일',
      'zh_Hans': '电子邮件',
    },
    'h5546n6k': {
      'en': 'Password',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'hi': 'पासवर्ड',
      'id': 'Kata sandi',
      'it': 'Password',
      'ja': 'パスワード',
      'ko': '비밀번호',
      'zh_Hans': '密码',
    },
    'dpnl6798': {
      'en': 'Confirm Password',
      'es': 'confirmar Contraseña',
      'fr': 'Confirmez le mot de passe',
      'hi': 'पासवर्ड की पुष्टि कीजिये',
      'id': 'Konfirmasi Kata Sandi',
      'it': 'Conferma password',
      'ja': 'パスワードを認証する',
      'ko': '비밀번호 확인',
      'zh_Hans': '确认密码',
    },
    'ifzwhrve': {
      'en': 'Create Account',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'hi': 'खाता बनाएं',
      'id': 'Buat Akun',
      'it': 'Creare un account',
      'ja': 'アカウントを作成する',
      'ko': '계정 생성',
      'zh_Hans': '创建账户',
    },
    'kfty848b': {
      'en': 'Create Account With Phone',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'hi': 'खाता बनाएं',
      'id': 'Buat Akun',
      'it': 'Creare un account',
      'ja': 'アカウントを作成する',
      'ko': '계정 생성',
      'zh_Hans': '创建账户',
    },
    'z9kzw84y': {
      'en':
          'By signing up, you agree to Versus Space’s \n    Terms of Service, Privacy Policy, and Cookie Policy.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '0ksnf2xz': {
      'en': 'Already have an account? ',
      'es': '¿Ya tienes una cuenta?',
      'fr': 'Vous avez déjà un compte ?',
      'hi': 'क्या आपके पास पहले से एक खाता मौजूद है?',
      'id': 'Sudah punya akun?',
      'it': 'Hai già un account?',
      'ja': 'すでにアカウントをお持ちですか?',
      'ko': '이미 계정이 있으신가요?',
      'zh_Hans': '已有账户？',
    },
    'do58zhdd': {
      'en': ' Log In here',
      'es': 'Inicie sesión aquí',
      'fr': 'loge ici',
      'hi': 'यहाँ लॉग इन करें',
      'id': 'Masuk ke sini',
      'it': 'log qui dentro',
      'ja': 'ログ ここ',
      'ko': 'loge 여기에',
      'zh_Hans': '在这里登记入住',
    },
    'sfx28arj': {
      'en': 'Email is required',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'fg4iipv6': {
      'en': 'Please enter a valid email address with domain.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'iagnl1sj': {
      'en': 'Please choose an option from the dropdown',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'c10h5qqp': {
      'en': 'Password is required',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'nlyzshnr': {
      'en': 'Please enter at least 8 characters.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'phds73eh': {
      'en': 'Please choose an option from the dropdown',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'dv9ttawj': {
      'en': 'Confirm Password is required',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'krbf7q4s': {
      'en': 'Please choose an option from the dropdown',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'a1t3yg9y': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
  },
  // Forgot_Password
  {
    'vczmwqaz': {
      'en': 'Back',
      'es': 'Atrás',
      'fr': 'Dos',
      'hi': 'पीछे',
      'id': 'Kembali',
      'it': 'Indietro',
      'ja': '戻る',
      'ko': '뒤쪽에',
      'zh_Hans': '后退',
    },
    '6adpvif5': {
      'en': 'Forgot Password',
      'es': 'Has olvidado tu contraseña',
      'fr': 'Mot de passe oublié',
      'hi': 'पासवर्ड भूल गए',
      'id': 'Lupa Kata Sandi',
      'it': 'Ha dimenticato la password',
      'ja': 'パスワードをお忘れですか',
      'ko': '비밀번호를 잊으셨나요?',
      'zh_Hans': '忘记密码',
    },
    'otjgw6ev': {
      'en':
          'We will send you an email with a link to reset your password, please enter the email associated with your account below.',
      'es':
          'Le enviaremos un correo electrónico con un enlace para restablecer su contraseña, ingrese el correo electrónico asociado a su cuenta a continuación.',
      'fr':
          'Nous vous enverrons un e-mail avec un lien pour réinitialiser votre mot de passe, veuillez saisir l\'e-mail associé à votre compte ci-dessous.',
      'hi':
          'हम आपको अपना पासवर्ड रीसेट करने के लिए एक लिंक के साथ एक ईमेल भेजेंगे, कृपया नीचे अपने खाते से संबद्ध ईमेल दर्ज करें।',
      'id':
          'Kami akan mengirimkan email berisi tautan untuk mengatur ulang kata sandi Anda, silakan masukkan email yang terkait dengan akun Anda di bawah ini.',
      'it':
          'Ti invieremo un\'e-mail con un link per reimpostare la tua password. Inserisci qui sotto l\'e-mail associata al tuo account.',
      'ja':
          'パスワードをリセットするためのリンクが記載されたメールをお送りしますので、アカウントに関連付けられているメールアドレスを以下に入力してください。',
      'ko': '비밀번호 재설정 링크가 포함된 이메일을 보내드리겠습니다. 아래에 귀하의 계정과 연결된 이메일을 입력하세요.',
      'zh_Hans': '我们将向您发送一封包含重置密码链接的电子邮件，请在下面输入与您的帐户关联的电子邮件。',
    },
    '8mw92l30': {
      'en': 'Your email address...',
      'es': 'Su dirección de correo electrónico...',
      'fr': 'Votre adresse e-mail...',
      'hi': 'आपका ईमेल पता...',
      'id': 'Alamat email Anda...',
      'it': 'Il tuo indirizzo di posta elettronica...',
      'ja': 'あなたのメールアドレス...',
      'ko': '귀하의 이메일 주소...',
      'zh_Hans': '您的电子邮件地址...',
    },
    'jabo9c3s': {
      'en': 'Enter your email...',
      'es': 'Introduce tu correo electrónico...',
      'fr': 'Entrez votre email...',
      'hi': 'अपना ईमेल दर्ज करें...',
      'id': 'Masukkan email Anda...',
      'it': 'Inserisci la tua email...',
      'ja': 'メールアドレスを入力してください...',
      'ko': '이메일을 입력하세요...',
      'zh_Hans': '输入您的电子邮件...',
    },
    '4rzuk0hj': {
      'en': 'Send Link',
      'es': 'Enviar enlace',
      'fr': 'Envoyer le lien',
      'hi': 'लिंक भेजें',
      'id': 'Kirim Tautan',
      'it': 'Invia collegamento',
      'ja': 'リンクを送信',
      'ko': '링크 보내기',
      'zh_Hans': '发送链接',
    },
    '7sfxx5v9': {
      'en': 'Back',
      'es': 'Atrás',
      'fr': 'Dos',
      'hi': 'पीछे',
      'id': 'Kembali',
      'it': 'Indietro',
      'ja': '戻る',
      'ko': '뒤쪽에',
      'zh_Hans': '后退',
    },
    'uhzqcthv': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'zh_Hans': '家',
    },
  },
  // user_info_input
  {
    'plunfug5': {
      'en': 'Information',
      'es': 'Información personal',
      'fr': 'Renseignements personnels',
      'hi': 'व्यक्तिगत जानकारी',
      'id': 'Informasi Pribadi',
      'it': 'Informazioni personali',
      'ja': '個人情報',
      'ko': '개인 정보',
      'zh_Hans': '个人信息',
    },
    '9bvrno9z': {
      'en': 'Display Name',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'm58rgdkp': {
      'en': 'Display name*',
      'es': 'Nombre de usuario*',
      'fr': 'Nom d\'utilisateur*',
      'hi': 'उपयोगकर्ता नाम*',
      'id': 'Nama belakang*',
      'it': 'Nome utente*',
      'ja': 'ユーザー名*',
      'ko': '사용자 이름*',
      'zh_Hans': '用户名*',
    },
    'pqx67cpq': {
      'en': 'Language',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'e2mae9l3': {
      'en': 'Gender',
      'es': 'Género',
      'fr': 'Genre',
      'hi': 'लिंग',
      'id': 'Jenis kelamin',
      'it': 'Genere',
      'ja': '性別',
      'ko': '성별',
      'zh_Hans': '性别',
    },
    'fy3unoj5': {
      'en': 'Female',
      'es': 'Femenino',
      'fr': 'Femelle',
      'hi': 'महिला',
      'id': 'Perempuan',
      'it': 'Femmina',
      'ja': '女性',
      'ko': '여성',
      'zh_Hans': '女性',
    },
    'sjv4inta': {
      'en': 'Male',
      'es': 'Masculino',
      'fr': 'Mâle',
      'hi': 'पुरुष',
      'id': 'Pria',
      'it': 'Maschio',
      'ja': '男',
      'ko': '남성',
      'zh_Hans': '男性',
    },
    'tmsnqk92': {
      'en': 'Other',
      'es': 'Otro',
      'fr': 'Autre',
      'hi': 'अन्य',
      'id': 'Lainnya',
      'it': 'Altro',
      'ja': '他の',
      'ko': '다른',
      'zh_Hans': '其他',
    },
    'cn54l9bj': {
      'en': 'I confirm that I am at least ',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'e8bfoncc': {
      'en': ' 13',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'eqbsqvs2': {
      'en': '  years old.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '4165t2cs': {
      'en':
          'If you are under 13, providing false or misleading \ninformation may subject you to legal or administrative consequences.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'k84ryt65': {
      'en': 'Continue',
      'es': 'Continuar',
      'fr': 'Continuer',
      'hi': 'जारी रखना',
      'id': 'Melanjutkan',
      'it': 'Continuare',
      'ja': '続く',
      'ko': '계속하다',
      'zh_Hans': '继续',
    },
    'u59p36mu': {
      'en': 'Please enter the your display name.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'b2ia6l1p': {
      'en': 'Please choose an option from the dropdown',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'jemkmkgu': {
      'en': 'Versus space',
      'es': 'versus espacio',
      'fr': 'contre l\'espace',
      'hi': 'बनाम अंतरिक्ष',
      'id': 'versus ruang',
      'it': 'contro lo spazio',
      'ja': '対宇宙',
      'ko': '우주에 대하여',
      'zh_Hans': '与空间',
    },
    'sb1a093z': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'zh_Hans': '家',
    },
  },
  // testpage_select
  {
    'r6d1yxm7': {
      'en': 'Hello World',
      'es': 'Hola Mundo',
      'fr': 'Bonjour le monde',
      'hi': 'हैलो वर्ल्ड',
      'id': 'Halo Dunia',
      'it': 'Ciao mondo',
      'ja': 'こんにちは世界',
      'ko': '안녕하세요 세상',
      'zh_Hans': '你好世界',
    },
    'x79ae4w2': {
      'en': 'Button',
      'es': 'Botón',
      'fr': 'Bouton',
      'hi': 'बटन',
      'id': 'Tombol',
      'it': 'Pulsante',
      'ja': 'ボタン',
      'ko': '단추',
      'zh_Hans': '按钮',
    },
    'y5m4a7vm': {
      'en': 'login',
      'es': 'Botón',
      'fr': 'Bouton',
      'hi': 'बटन',
      'id': 'Tombol',
      'it': 'Pulsante',
      'ja': 'ボタン',
      'ko': '단추',
      'zh_Hans': '按钮',
    },
    'df9krpqf': {
      'en': 'creat_ac',
      'es': 'Botón',
      'fr': 'Bouton',
      'hi': 'बटन',
      'id': 'Tombol',
      'it': 'Pulsante',
      'ja': 'ボタン',
      'ko': '단추',
      'zh_Hans': '按钮',
    },
    'unrhe499': {
      'en': 'forgot_ps',
      'es': 'Botón',
      'fr': 'Bouton',
      'hi': 'बटन',
      'id': 'Tombol',
      'it': 'Pulsante',
      'ja': 'ボタン',
      'ko': '단추',
      'zh_Hans': '按钮',
    },
    'd4vvfi1v': {
      'en': 'user_info\n',
      'es': 'Botón',
      'fr': 'Bouton',
      'hi': 'बटन',
      'id': 'Tombol',
      'it': 'Pulsante',
      'ja': 'ボタン',
      'ko': '단추',
      'zh_Hans': '按钮',
    },
    'e17ogwad': {
      'en': 'jopselect\n',
      'es': 'Botón',
      'fr': 'Bouton',
      'hi': 'बटन',
      'id': 'Tombol',
      'it': 'Pulsante',
      'ja': 'ボタン',
      'ko': '단추',
      'zh_Hans': '按钮',
    },
    '4ffxgxck': {
      'en': 'testalgolia\n',
      'es': 'Botón',
      'fr': 'Bouton',
      'hi': 'बटन',
      'id': 'Tombol',
      'it': 'Pulsante',
      'ja': 'ボタン',
      'ko': '단추',
      'zh_Hans': '按钮',
    },
    '87ap5nug': {
      'en': 'start',
      'es': 'Botón',
      'fr': 'Bouton',
      'hi': 'बटन',
      'id': 'Tombol',
      'it': 'Pulsante',
      'ja': 'ボタン',
      'ko': '단추',
      'zh_Hans': '按钮',
    },
    'oadbd0gy': {
      'en': 'phonelogin',
      'es': 'Botón',
      'fr': 'Bouton',
      'hi': 'बटन',
      'id': 'Tombol',
      'it': 'Pulsante',
      'ja': 'ボタン',
      'ko': '단추',
      'zh_Hans': '按钮',
    },
    '5fjkgyoa': {
      'en': 'homeAPosts\n',
      'es': 'Botón',
      'fr': 'Bouton',
      'hi': 'बटन',
      'id': 'Tombol',
      'it': 'Pulsante',
      'ja': 'ボタン',
      'ko': '단추',
      'zh_Hans': '按钮',
    },
    'pckw648z': {
      'en': 'editvideo',
      'es': 'Botón',
      'fr': 'Bouton',
      'hi': 'बटन',
      'id': 'Tombol',
      'it': 'Pulsante',
      'ja': 'ボタン',
      'ko': '단추',
      'zh_Hans': '按钮',
    },
    'un1ogy5i': {
      'en': 'Button',
      'es': 'Botón',
      'fr': 'Bouton',
      'hi': 'बटन',
      'id': 'Tombol',
      'it': 'Pulsante',
      'ja': 'ボタン',
      'ko': '단추',
      'zh_Hans': '按钮',
    },
    'ln1qokjg': {
      'en': 'Button',
      'es': 'Botón',
      'fr': 'Bouton',
      'hi': 'बटन',
      'id': 'Tombol',
      'it': 'Pulsante',
      'ja': 'ボタン',
      'ko': '단추',
      'zh_Hans': '按钮',
    },
    'rbd8xke9': {
      'en': 'versus space',
      'es': 'versus espacio',
      'fr': 'contre l\'espace',
      'hi': 'बनाम अंतरिक्ष',
      'id': 'versus ruang',
      'it': 'contro lo spazio',
      'ja': '対宇宙',
      'ko': '우주에 대하여',
      'zh_Hans': '与空间',
    },
    'cu01fdr4': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'zh_Hans': '家',
    },
  },
  // expertise_select
  {
    'lfhxure4': {
      'en': ', Tell us your expertise,',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'wdoi0lud': {
      'en': '\nwe’ll send you better questions.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'crcvslnv': {
      'en': 'What’s your area of expertise?',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'xirl42y4': {
      'en': 'expertise...',
      'es': 'Nombre de usuario*',
      'fr': 'Nom d\'utilisateur*',
      'hi': 'उपयोगकर्ता नाम*',
      'id': 'Nama belakang*',
      'it': 'Nome utente*',
      'ja': 'ユーザー名*',
      'ko': '사용자 이름*',
      'zh_Hans': '用户名*',
    },
    '5pspjm2b': {
      'en': 'You can add up to 4 items.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '2l833og3': {
      'en': 'Add',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'qvwfh5oz': {
      'en': 'List.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'jvb8485b': {
      'en': 'Tip.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'r2cx59n4': {
      'en':
          ' Add your expertise tags (e.g. #coding, #investment) to see questions tailored to your interests.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'qdcvozij': {
      'en':
          '\n\n\"Which of these two coding frameworks should I use for my new project?\"',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'qoetb929': {
      'en': '\n“Which tool is easier for beginner investors, A or B?”',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'nb2efhx9': {
      'en': 'Next',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '519xixp4': {
      'en': 'versus space',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'sf4vca89': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'zh_Hans': '家',
    },
  },
  // testalgoria
  {
    '4ofzrgyp': {
      'en': 'TextField',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'fafdx2pw': {
      'en': 'Page Title',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '3miu98e5': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'zh_Hans': '家',
    },
  },
  // hobbies_select
  {
    'jnha4tov': {
      'en': ' Next, share your hobbies and interests!',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    's6khifdw': {
      'en': '\nWe’ll tailor recommendations to your personal passions.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '8cyk6y1f': {
      'en': 'What are your hobbies or interests?',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'kh1x2j64': {
      'en': 'hobby or interest…',
      'es': 'Nombre de usuario*',
      'fr': 'Nom d\'utilisateur*',
      'hi': 'उपयोगकर्ता नाम*',
      'id': 'Nama belakang*',
      'it': 'Nome utente*',
      'ja': 'ユーザー名*',
      'ko': '사용자 이름*',
      'zh_Hans': '用户名*',
    },
    'qdn4sbni': {
      'en': 'You can add up to 8 items.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '0a61zfnb': {
      'en': 'Add',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'tial28r9': {
      'en': 'List.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'ddy2vf0h': {
      'en': 'Tip.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'ap7dkw8g': {
      'en':
          ' Add your favorite hobbies or interests (e.g. #travel, #sports) to see content tailored to your passions.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'r0p1jhwa': {
      'en':
          '\n\n“Which instrument is more beginner-friendly, guitar or piano?”',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'ng6aurtj': {
      'en':
          '\n“For a short getaway, would you prefer a guided city tour or a nature retreat?”',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '0m7oqr3n': {
      'en': 'Next',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'flvvuyvo': {
      'en': 'versus space',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'prkzyejg': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'zh_Hans': '家',
    },
  },
  // agrred_select
  {
    '17zx9oh1': {
      'en': ' Next, share your hobbies and interests!',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'xxz7ej5s': {
      'en': '\nWe’ll tailor recommendations to your personal passions.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'u7v4k6jw': {
      'en': 'What are your hobbies or interests?',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '278cy82i': {
      'en': 'hobby or interest…',
      'es': 'Nombre de usuario*',
      'fr': 'Nom d\'utilisateur*',
      'hi': 'उपयोगकर्ता नाम*',
      'id': 'Nama belakang*',
      'it': 'Nome utente*',
      'ja': 'ユーザー名*',
      'ko': '사용자 이름*',
      'zh_Hans': '用户名*',
    },
    'zpkdrkrf': {
      'en': 'You can add up to 8 items.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'ij0f81vj': {
      'en': 'Add',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'okzh5b2z': {
      'en': 'List.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'medehueg': {
      'en': 'Tip.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '1ppulwvg': {
      'en':
          ' Add your favorite hobbies or interests (e.g. #travel, #sports) to see content tailored to your passions.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'bsanq3ez': {
      'en':
          '\n\n“Which instrument is more beginner-friendly, guitar or piano?”',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'k1wz4a90': {
      'en':
          '\n“For a short getaway, would you prefer a guided city tour or a nature retreat?”',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'i8rpxq4t': {
      'en': 'Next',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '1kaqp8o7': {
      'en': 'versus space',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '6oe2nnzd': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'zh_Hans': '家',
    },
  },
  // start_page
  {
    'ur72jrvo': {
      'en': 'Life is a \'c\' between \'b\' and \'d\'',
      'es': 'La vida es una \'c\' entre \'b\' y \'d\'',
      'fr': 'La vie est un « c » entre « b » et « d »',
      'hi': 'जीवन \'बी\' और \'डी\' के बीच का \'सी\' है',
      'id': 'Hidup adalah huruf \'c\' antara \'b\' dan \'d\'',
      'it': 'La vita è una \"c\" tra \"b\" e \"d\"',
      'ja': '人生は「b」と「d」の間の「c」である',
      'ko': '인생은 \'b\'와 \'d\' 사이의 \'c\'입니다',
      'zh_Hans': '生命是介于“b”和“d”之间的“c”',
    },
    'tkccfqfy': {
      'en': 'Go To Create Account',
      'es': 'Ir a Crear cuenta',
      'fr': 'Aller à Créer un compte',
      'hi': 'खाता बनाने के लिए जाएँ',
      'id': 'Buka Buat Akun',
      'it': 'Vai a Crea account',
      'ja': 'アカウント作成へ進む',
      'ko': '계정 만들기로 이동',
      'zh_Hans': '前往创建账户',
    },
    '3gnrvqoi': {
      'en': 'Continue with Apple',
      'es': 'Continuar con Apple',
      'fr': 'Continuer avec Apple',
      'hi': 'एप्पल के साथ जारी रखें',
      'id': 'Lanjutkan dengan Apple',
      'it': 'Continua con Apple',
      'ja': 'Appleで続ける',
      'ko': 'Apple로 계속하기',
      'zh_Hans': '继续使用 Apple',
    },
    's24g5s5d': {
      'en': 'Continue with Google',
      'es': 'Continuar con Google',
      'fr': 'Continuer avec Google',
      'hi': 'Google के साथ जारी रखें',
      'id': 'Lanjutkan dengan Google',
      'it': 'Continua con Google',
      'ja': 'Googleで続行',
      'ko': 'Google로 계속하기',
      'zh_Hans': '继续使用 Google',
    },
    'ntv3cl1f': {
      'en': 'Continue with Facebook',
      'es': 'Continuar con Facebook',
      'fr': 'Continuer avec Facebook',
      'hi': 'फेसबुक के साथ जारी रखें',
      'id': 'Lanjutkan dengan Facebook',
      'it': 'Continua con Facebook',
      'ja': 'Facebookで続ける',
      'ko': 'Facebook으로 계속하기',
      'zh_Hans': '继续使用 Facebook',
    },
    '4ssf49xr': {
      'en': 'Continue with Instagram',
      'es': 'Continuar con Instagram',
      'fr': 'Continuer avec Instagram',
      'hi': 'इंस्टाग्राम पर जारी रखें',
      'id': 'Lanjutkan dengan Instagram',
      'it': 'Continua con Instagram',
      'ja': 'Instagramで続ける',
      'ko': '인스타그램을 계속하세요',
      'zh_Hans': '继续使用 Instagram',
    },
    'b71h3bzp': {
      'en': 'Go To Sign in',
      'es': 'Ir a Iniciar sesión',
      'fr': 'Accéder à la connexion',
      'hi': 'साइन इन पर जाएँ',
      'id': 'Pergi ke Masuk',
      'it': 'Vai a Accedi',
      'ja': 'サインインへ進む',
      'ko': '로그인으로 이동',
      'zh_Hans': '前往登录',
    },
    'x52aa05l': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'zh_Hans': '家',
    },
  },
  // testdivider
  {
    '820vo5vt': {
      'en': 'Page Title',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    's2ndilcz': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
  },
  // PhoneCreatAccount
  {
    'gwbbszpy': {
      'en': 'Phone Login',
      'es': 'Has olvidado tu contraseña',
      'fr': 'Mot de passe oublié',
      'hi': 'पासवर्ड भूल गए',
      'id': 'Lupa Kata Sandi',
      'it': 'Ha dimenticato la password',
      'ja': 'パスワードをお忘れですか',
      'ko': '비밀번호를 잊으셨나요?',
      'zh_Hans': '忘记密码',
    },
    'xv3gqx8x': {
      'en':
          'Please enter your phone number below.\nWe’ll send a verification code via SMS.\nOnce you receive the code, enter it here to log in.',
      'es':
          'Le enviaremos un correo electrónico con un enlace para restablecer su contraseña, ingrese el correo electrónico asociado a su cuenta a continuación.',
      'fr':
          'Nous vous enverrons un e-mail avec un lien pour réinitialiser votre mot de passe, veuillez saisir l\'e-mail associé à votre compte ci-dessous.',
      'hi':
          'हम आपको अपना पासवर्ड रीसेट करने के लिए एक लिंक के साथ एक ईमेल भेजेंगे, कृपया नीचे अपने खाते से संबद्ध ईमेल दर्ज करें।',
      'id':
          'Kami akan mengirimkan email berisi tautan untuk mengatur ulang kata sandi Anda, silakan masukkan email yang terkait dengan akun Anda di bawah ini.',
      'it':
          'Ti invieremo un\'e-mail con un link per reimpostare la tua password. Inserisci qui sotto l\'e-mail associata al tuo account.',
      'ja':
          'パスワードをリセットするためのリンクが記載されたメールをお送りしますので、アカウントに関連付けられているメールアドレスを以下に入力してください。',
      'ko': '비밀번호 재설정 링크가 포함된 이메일을 보내드리겠습니다. 아래에 귀하의 계정과 연결된 이메일을 입력하세요.',
      'zh_Hans': '我们将向您发送一封包含重置密码链接的电子邮件，请在下面输入与您的帐户关联的电子邮件。',
    },
    '3rvgi38u': {
      'en': '+Code',
      'es': 'Su dirección de correo electrónico...',
      'fr': 'Votre adresse e-mail...',
      'hi': 'आपका ईमेल पता...',
      'id': 'Alamat email Anda...',
      'it': 'Il tuo indirizzo di posta elettronica...',
      'ja': 'あなたのメールアドレス...',
      'ko': '귀하의 이메일 주소...',
      'zh_Hans': '您的电子邮件地址...',
    },
    'kna6yami': {
      'en': 'Your Phone Number...',
      'es': 'Su dirección de correo electrónico...',
      'fr': 'Votre adresse e-mail...',
      'hi': 'आपका ईमेल पता...',
      'id': 'Alamat email Anda...',
      'it': 'Il tuo indirizzo di posta elettronica...',
      'ja': 'あなたのメールアドレス...',
      'ko': '귀하의 이메일 주소...',
      'zh_Hans': '您的电子邮件地址...',
    },
    'npd3p5vi': {
      'en': 'Enter your Phone Number...',
      'es': 'Introduce tu correo electrónico...',
      'fr': 'Entrez votre email...',
      'hi': 'अपना ईमेल दर्ज करें...',
      'id': 'Masukkan email Anda...',
      'it': 'Inserisci la tua email...',
      'ja': 'メールアドレスを入力してください...',
      'ko': '이메일을 입력하세요...',
      'zh_Hans': '输入您的电子邮件...',
    },
    'pqidvgqu': {
      'en': 'Send  Code',
      'es': 'Enviar enlace',
      'fr': 'Envoyer le lien',
      'hi': 'लिंक भेजें',
      'id': 'Kirim Tautan',
      'it': 'Invia collegamento',
      'ja': 'リンクを送信',
      'ko': '링크 보내기',
      'zh_Hans': '发送链接',
    },
    'qgyftxro': {
      'en': 'Back',
      'es': 'Atrás',
      'fr': 'Dos',
      'hi': 'पीछे',
      'id': 'Kembali',
      'it': 'Indietro',
      'ja': '戻る',
      'ko': '뒤쪽에',
      'zh_Hans': '后退',
    },
    '599ek3fb': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'zh_Hans': '家',
    },
  },
  // Phonelogeinpincode
  {
    'daf828ek': {
      'en': 'Phone Login',
      'es': 'Has olvidado tu contraseña',
      'fr': 'Mot de passe oublié',
      'hi': 'पासवर्ड भूल गए',
      'id': 'Lupa Kata Sandi',
      'it': 'Ha dimenticato la password',
      'ja': 'パスワードをお忘れですか',
      'ko': '비밀번호를 잊으셨나요?',
      'zh_Hans': '忘记密码',
    },
    'ddk0vrr5': {
      'en':
          'Please enter your phone number below.\nWe’ll send a verification code via SMS.\nOnce you receive the code, enter it here to log in.',
      'es':
          'Le enviaremos un correo electrónico con un enlace para restablecer su contraseña, ingrese el correo electrónico asociado a su cuenta a continuación.',
      'fr':
          'Nous vous enverrons un e-mail avec un lien pour réinitialiser votre mot de passe, veuillez saisir l\'e-mail associé à votre compte ci-dessous.',
      'hi':
          'हम आपको अपना पासवर्ड रीसेट करने के लिए एक लिंक के साथ एक ईमेल भेजेंगे, कृपया नीचे अपने खाते से संबद्ध ईमेल दर्ज करें।',
      'id':
          'Kami akan mengirimkan email berisi tautan untuk mengatur ulang kata sandi Anda, silakan masukkan email yang terkait dengan akun Anda di bawah ini.',
      'it':
          'Ti invieremo un\'e-mail con un link per reimpostare la tua password. Inserisci qui sotto l\'e-mail associata al tuo account.',
      'ja':
          'パスワードをリセットするためのリンクが記載されたメールをお送りしますので、アカウントに関連付けられているメールアドレスを以下に入力してください。',
      'ko': '비밀번호 재설정 링크가 포함된 이메일을 보내드리겠습니다. 아래에 귀하의 계정과 연결된 이메일을 입력하세요.',
      'zh_Hans': '我们将向您发送一封包含重置密码链接的电子邮件，请在下面输入与您的帐户关联的电子邮件。',
    },
    '6lsg39md': {
      'en': '\nEnter the 6-digit code sent to your phone.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'ep61t57h': {
      'en': 'Authentication succeeded!!',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '85h4oe02': {
      'en': 'Authentication failed. Please try again.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '7ezietmr': {
      'en': 'Re Code',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'pyfnfxye': {
      'en':
          'Tip. If you haven’t received it, try resending or check your phone number.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'xjt78grf': {
      'en': 'Next',
      'es': 'Enviar enlace',
      'fr': 'Envoyer le lien',
      'hi': 'लिंक भेजें',
      'id': 'Kirim Tautan',
      'it': 'Invia collegamento',
      'ja': 'リンクを送信',
      'ko': '링크 보내기',
      'zh_Hans': '发送链接',
    },
    'bjt41bts': {
      'en': 'Back',
      'es': 'Atrás',
      'fr': 'Dos',
      'hi': 'पीछे',
      'id': 'Kembali',
      'it': 'Indietro',
      'ja': '戻る',
      'ko': '뒤쪽에',
      'zh_Hans': '后退',
    },
    '8wbm2zg3': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'zh_Hans': '家',
    },
  },
  // blankppp
  {
    '0y0b5bpx': {
      'en': 'Page Title',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'erkqyrow': {
      'en': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'hi': 'ईमेल',
      'id': 'E-mail',
      'it': 'E-mail',
      'ja': 'メール',
      'ko': '이메일',
      'zh_Hans': '电子邮件',
    },
    'tcloodtg': {
      'en': 'Password',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'hi': 'पासवर्ड',
      'id': 'Kata sandi',
      'it': 'Password',
      'ja': 'パスワード',
      'ko': '비밀번호',
      'zh_Hans': '密码',
    },
    '0qwo5ebl': {
      'en': 'log in',
      'es': 'acceso',
      'fr': 'se connecter',
      'hi': 'लॉग इन करें',
      'id': 'Masuk',
      'it': 'login',
      'ja': 'ログイン',
      'ko': '로그인하다',
      'zh_Hans': '登录',
    },
    'mgoq8vt1': {
      'en': 'Forgot Password',
      'es': 'Has olvidado tu contraseña',
      'fr': 'Mot de passe oublié',
      'hi': 'पासवर्ड भूल गए',
      'id': 'Lupa Kata Sandi',
      'it': 'Ha dimenticato la password',
      'ja': 'パスワードをお忘れですか',
      'ko': '비밀번호를 잊으셨나요?',
      'zh_Hans': '忘记密码',
    },
    's44z3wif': {
      'en': 'Or sign up with, goto test',
      'es': 'O regístrate con',
      'fr': 'Ou inscrivez-vous avec',
      'hi': 'या साइन अप करें',
      'id': 'Atau daftar dengan',
      'it': 'Oppure registrati con',
      'ja': 'またはサインアップ',
      'ko': '또는 가입하세요',
      'zh_Hans': '或注册',
    },
    'zg9cqede': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
  },
  // HomeAndPosts
  {
    'x39v6lyp': {
      'en': 'Page Title',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '100mlae4': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
  },
  // HomeAndPostsCopy
  {
    'cksdlwvw': {
      'en': 'Page Title',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'xwrcpz9v': {
      'en': 'A',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'hddxeylg': {
      'en': 'B',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'g32j8ys3': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
  },
  // editvideoP
  {
    '6vxfvxd1': {
      'en': 'upload',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'v6lswlmj': {
      'en': 'cancle',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'imk8y17a': {
      'en': 'Page Title',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'ufuh95zc': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
  },
  // editvideopp
  {
    'px8eovob': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
  },
  // TagsLabels
  {
    'hq8fohiq': {
      'en': '#website',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'zpugyk8p': {
      'en': '#ux',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '3rcbycua': {
      'en': '#flutterflow',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
  },
  // vsmark
  {
    'abejuxne': {
      'en': 'Versus',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': 'Versus',
      'ko': 'Versus',
      'zh_Hans': 'Versus',
    },
  },
  // PopupTimerEmail
  {
    'ajk36y0p': {
      'en': 'Email verification in progress.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'zustpgk9': {
      'en': 'Check your Email,\n',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'c3ope0t7': {
      'en': 'Edit Email..',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'yqb182uz': {
      'en': 'Re Send..',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
  },
  // Phonemaximum
  {
    '3dcoy1cp': {
      'en': 'You have exceeded the maximum of 3 resend attempts.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'vgyx5a8r': {
      'en': 'Ok',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
  },
  // Phoneloginpincode
  {
    'usvyes4j': {
      'en': 'Email verification in progress.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'h0xldpn5': {
      'en': 'Check your Email,\n',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'w7b2rjfw': {
      'en': 'Hello World',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
  },
  // CharacterDetailPage
  {
    '5dgi9ixf': {
      'en': 'Apply',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'jtczffcg': {
      'en': 'Gallery / Camera',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
  },
  // InPutText
  {
    'w5drxgwf': {
      'en': 'TextField',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '0zfp2fn2': {
      'en': 'sheetText is required',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '1k8j3n9p': {
      'en': 'Please choose an option from the dropdown',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'uvtnvfi7': {
      'en': 'Button',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'prw75byg': {
      'en': 'Hello World',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
  },
  // InPutImage
  {
    'yaggfmwm': {
      'en': 'Gallary',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '63hun11y': {
      'en': 'Camera',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'bwlvl54v': {
      'en': 'Button',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'k73btvmc': {
      'en': 'Hello World',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
  },
  // emptyalert
  {
    'd0ji9xsm': {
      'en': 'No Text Entered',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '8iwxyn0s': {
      'en':
          'The text field is empty. If you close now, your previously saved text will be lost.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '5noy5w0s': {
      'en': 'Ok',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
  },
  // alertempty
  {
    '707q86sk': {
      'en': 'No Text Entered',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'sz1sjey3': {
      'en':
          'The text field is empty. If you close now, your previously saved text will be lost.',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'xhyu1hyf': {
      'en': 'Ok',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
  },
  // InPutIvideo
  {
    '5j8wn3ec': {
      'en': 'Gallary',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '6qo02jch': {
      'en': 'Back',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'wg4l2nxs': {
      'en': 'apply',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '7ngao819': {
      'en': 'YuTube',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'qh625dmg': {
      'en': 'YouTube',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '7gqk5lt5': {
      'en': 'TextField',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'bzs7qsx8': {
      'en': 'Link',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '171yaxvn': {
      'en': 'Link    ',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'ehmkbuuc': {
      'en': '- Shorts',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'jtwrhql9': {
      'en': 'TextField',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '448u8u21': {
      'en': 'Apply',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'hy93en4y': {
      'en': 'Hello World',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
  },
  // editviedo
  {
    '613h5dwl': {
      'en': 'Hello World',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'h9yoweew': {
      'en': 'Hello World',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'g405hkr8': {
      'en': 'upload',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'r3qip94t': {
      'en': 'cancle',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
  },
  // Miscellaneous
  {
    '29m1hzk8': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'yh7e4qeq': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'gp947i66': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'tr194mk6': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'rbopmhq9': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '1bljlacq': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'i73k5t8v': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'ao9qmgqm': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'm7jdnh1u': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '3o3nn93a': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'jd9hhqz8': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'jlsw03bu': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '5uwu5vul': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'l2fx117x': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '66absala': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'eorrndcb': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'b3dl38xi': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '4st3oxse': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'exqyr4ok': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'nlmzt7vq': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '774e6yf3': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'v9r77mba': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'a5gxuhtu': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'bk9ujrc5': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'dct26121': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'jstic31n': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    '82w032fm': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
    'jfr76ob1': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
