// Mocks generated by Mockito 5.4.6 from annotations
// in versus_space/test/features/auth/domain/usecases/phone/send_phone_otp_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:versus_space/features/auth/domain/entities/auth_user.dart'
    as _i4;
import 'package:versus_space/features/auth/domain/failures/auth_failure.dart'
    as _i6;
import 'package:versus_space/features/auth/domain/repositories/i_auth_repository.dart'
    as _i2;
import 'package:versus_space/services/rate_limit/rate_limit_service.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthRepository extends _i1.Mock implements _i2.IAuthRepository {
  @override
  bool get isSignedIn =>
      (super.noSuchMethod(
            Invocation.getter(#isSignedIn),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Stream<_i4.AuthUser?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i3.Stream<_i4.AuthUser?>.empty(),
            returnValueForMissingStub: _i3.Stream<_i4.AuthUser?>.empty(),
          )
          as _i3.Stream<_i4.AuthUser?>);

  @override
  _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue:
                _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>.value(
                  _i7.dummyValue<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>(
                    this,
                    Invocation.method(#getCurrentUser, []),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>.value(
                  _i7.dummyValue<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>(
                    this,
                    Invocation.method(#getCurrentUser, []),
                  ),
                ),
          )
          as _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>);

  @override
  _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>
  signInWithEmailAndPassword(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue:
                _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>.value(
                  _i7.dummyValue<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>(
                    this,
                    Invocation.method(#signInWithEmailAndPassword, [
                      email,
                      password,
                    ]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>.value(
                  _i7.dummyValue<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>(
                    this,
                    Invocation.method(#signInWithEmailAndPassword, [
                      email,
                      password,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>);

  @override
  _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>
  createUserWithEmailAndPassword(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#createUserWithEmailAndPassword, [
              email,
              password,
            ]),
            returnValue:
                _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>.value(
                  _i7.dummyValue<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>(
                    this,
                    Invocation.method(#createUserWithEmailAndPassword, [
                      email,
                      password,
                    ]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>.value(
                  _i7.dummyValue<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>(
                    this,
                    Invocation.method(#createUserWithEmailAndPassword, [
                      email,
                      password,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>);

  @override
  _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue:
                _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>.value(
                  _i7.dummyValue<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>(
                    this,
                    Invocation.method(#signInWithGoogle, []),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>.value(
                  _i7.dummyValue<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>(
                    this,
                    Invocation.method(#signInWithGoogle, []),
                  ),
                ),
          )
          as _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>);

  @override
  _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue:
                _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>.value(
                  _i7.dummyValue<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>(
                    this,
                    Invocation.method(#signInWithApple, []),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>.value(
                  _i7.dummyValue<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>(
                    this,
                    Invocation.method(#signInWithApple, []),
                  ),
                ),
          )
          as _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>);

  @override
  _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>> signInWithPhoneNumber(
    String? phoneNumber,
    String? verificationCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPhoneNumber, [
              phoneNumber,
              verificationCode,
            ]),
            returnValue:
                _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>.value(
                  _i7.dummyValue<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>(
                    this,
                    Invocation.method(#signInWithPhoneNumber, [
                      phoneNumber,
                      verificationCode,
                    ]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>.value(
                  _i7.dummyValue<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>(
                    this,
                    Invocation.method(#signInWithPhoneNumber, [
                      phoneNumber,
                      verificationCode,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i5.Either<_i6.AuthFailure, _i4.AuthUser>>);

  @override
  _i3.Future<_i5.Either<_i6.AuthFailure, bool>> sendSmsOtp(
    String? phoneNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendSmsOtp, [phoneNumber]),
            returnValue: _i3.Future<_i5.Either<_i6.AuthFailure, bool>>.value(
              _i7.dummyValue<_i5.Either<_i6.AuthFailure, bool>>(
                this,
                Invocation.method(#sendSmsOtp, [phoneNumber]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i5.Either<_i6.AuthFailure, bool>>.value(
                  _i7.dummyValue<_i5.Either<_i6.AuthFailure, bool>>(
                    this,
                    Invocation.method(#sendSmsOtp, [phoneNumber]),
                  ),
                ),
          )
          as _i3.Future<_i5.Either<_i6.AuthFailure, bool>>);

  @override
  _i3.Future<_i5.Either<_i6.AuthFailure, void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<_i5.Either<_i6.AuthFailure, void>>.value(
              _i7.dummyValue<_i5.Either<_i6.AuthFailure, void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i5.Either<_i6.AuthFailure, void>>.value(
                  _i7.dummyValue<_i5.Either<_i6.AuthFailure, void>>(
                    this,
                    Invocation.method(#signOut, []),
                  ),
                ),
          )
          as _i3.Future<_i5.Either<_i6.AuthFailure, void>>);

  @override
  _i3.Future<_i5.Either<_i6.AuthFailure, void>> sendPasswordResetEmail(
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i3.Future<_i5.Either<_i6.AuthFailure, void>>.value(
              _i7.dummyValue<_i5.Either<_i6.AuthFailure, void>>(
                this,
                Invocation.method(#sendPasswordResetEmail, [email]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i5.Either<_i6.AuthFailure, void>>.value(
                  _i7.dummyValue<_i5.Either<_i6.AuthFailure, void>>(
                    this,
                    Invocation.method(#sendPasswordResetEmail, [email]),
                  ),
                ),
          )
          as _i3.Future<_i5.Either<_i6.AuthFailure, void>>);

  @override
  _i3.Future<_i5.Either<_i6.AuthFailure, bool>> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i3.Future<_i5.Either<_i6.AuthFailure, bool>>.value(
              _i7.dummyValue<_i5.Either<_i6.AuthFailure, bool>>(
                this,
                Invocation.method(#sendEmailVerification, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i5.Either<_i6.AuthFailure, bool>>.value(
                  _i7.dummyValue<_i5.Either<_i6.AuthFailure, bool>>(
                    this,
                    Invocation.method(#sendEmailVerification, []),
                  ),
                ),
          )
          as _i3.Future<_i5.Either<_i6.AuthFailure, bool>>);

  @override
  _i3.Future<_i5.Either<_i6.AuthFailure, bool>> deleteUser() =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, []),
            returnValue: _i3.Future<_i5.Either<_i6.AuthFailure, bool>>.value(
              _i7.dummyValue<_i5.Either<_i6.AuthFailure, bool>>(
                this,
                Invocation.method(#deleteUser, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i5.Either<_i6.AuthFailure, bool>>.value(
                  _i7.dummyValue<_i5.Either<_i6.AuthFailure, bool>>(
                    this,
                    Invocation.method(#deleteUser, []),
                  ),
                ),
          )
          as _i3.Future<_i5.Either<_i6.AuthFailure, bool>>);

  @override
  _i3.Future<_i5.Either<_i6.AuthFailure, void>> updateUserProfile({
    String? displayName,
    String? photoURL,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [], {
              #displayName: displayName,
              #photoURL: photoURL,
            }),
            returnValue: _i3.Future<_i5.Either<_i6.AuthFailure, void>>.value(
              _i7.dummyValue<_i5.Either<_i6.AuthFailure, void>>(
                this,
                Invocation.method(#updateUserProfile, [], {
                  #displayName: displayName,
                  #photoURL: photoURL,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i5.Either<_i6.AuthFailure, void>>.value(
                  _i7.dummyValue<_i5.Either<_i6.AuthFailure, void>>(
                    this,
                    Invocation.method(#updateUserProfile, [], {
                      #displayName: displayName,
                      #photoURL: photoURL,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i5.Either<_i6.AuthFailure, void>>);

  @override
  _i3.Future<_i5.Either<_i6.AuthFailure, bool>> updatePassword(
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i3.Future<_i5.Either<_i6.AuthFailure, bool>>.value(
              _i7.dummyValue<_i5.Either<_i6.AuthFailure, bool>>(
                this,
                Invocation.method(#updatePassword, [newPassword]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i5.Either<_i6.AuthFailure, bool>>.value(
                  _i7.dummyValue<_i5.Either<_i6.AuthFailure, bool>>(
                    this,
                    Invocation.method(#updatePassword, [newPassword]),
                  ),
                ),
          )
          as _i3.Future<_i5.Either<_i6.AuthFailure, bool>>);
}

/// A class which mocks [RateLimitService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRateLimitService extends _i1.Mock implements _i8.RateLimitService {
  @override
  _i3.Future<bool> canPerformAction({
    required String? userId,
    required _i8.RateLimitAction? action,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#canPerformAction, [], {
              #userId: userId,
              #action: action,
            }),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> recordAction({
    required String? userId,
    required _i8.RateLimitAction? action,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordAction, [], {
              #userId: userId,
              #action: action,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getRemainingRequests({
    required String? userId,
    required _i8.RateLimitAction? action,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRemainingRequests, [], {
              #userId: userId,
              #action: action,
            }),
            returnValue: _i3.Future<int>.value(0),
            returnValueForMissingStub: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<Duration?> getTimeUntilNextRequest({
    required String? userId,
    required _i8.RateLimitAction? action,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTimeUntilNextRequest, [], {
              #userId: userId,
              #action: action,
            }),
            returnValue: _i3.Future<Duration?>.value(),
            returnValueForMissingStub: _i3.Future<Duration?>.value(),
          )
          as _i3.Future<Duration?>);

  @override
  _i3.Future<void> resetLimit({
    required String? userId,
    required _i8.RateLimitAction? action,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetLimit, [], {
              #userId: userId,
              #action: action,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cleanupOldEntries() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupOldEntries, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
