#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
CodeSurgeon - 큰 파일에서 지정 심볼을 새 파일로 추출 (간단 스텁)
"""
import argparse, re, sys, difflib
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
PATCHES = ROOT/"patches"; REPORTS = ROOT/"reports"
for d in (PATCHES, REPORTS): d.mkdir(exist_ok=True)

CLASS_RE = re.compile(r'^(class|mixin|extension)\s+(\w+)\b', re.M)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--file", required=True)
    ap.add_argument("--map", required=True, help="Sym->lib/features/...;Sym2->...")
    ap.add_argument("--mode", choices=["detect","apply"], default="detect")
    args = ap.parse_args()

    srcp = ROOT/args.file
    src = srcp.read_text(encoding="utf-8")
    symbols = {a.strip():Path(b.strip()) for a,b in (s.split("->") for s in args.map.split(";") if "->" in s)}

    changes=[]
    for sym, dst in symbols.items():
        content = f"// GENERATED by CodeSurgeon\n// extracted: {sym}\n"
        old = dst.read_text(encoding="utf-8") if dst.exists() else ""
        changes.append((dst, old, content))

    # 원본은 그대로(보수적), 차후 개선
    import difflib
    patch = PATCHES/f"code_surgeon_{srcp.stem}.diff"
    diff=[]
    for p, old, new in changes:
        a=old.splitlines(True); b=new.splitlines(True)
        rel=str(p.relative_to(ROOT))
        diff += list(difflib.unified_diff(a,b,fromfile=f"a/{rel}",tofile=f"b/{rel}",lineterm=""))
    patch.write_text("\n".join(diff), encoding="utf-8")
    REPORTS/f"code_surgeon_{srcp.stem}.yml".write_text(
        f"file: {args.file}\npatch: {patch}\nmode: {args.mode}\ncreated: {len(changes)}\n", encoding="utf-8"
    )
    if args.mode=="apply":
        for p, old, new in changes:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(new, encoding="utf-8")
    print(f"[CodeSurgeon] patch -> {patch} (mode={args.mode})")

if __name__=="__main__":
    sys.exit(main())
