#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
RouterSplitter - app/router.dart 비대 라우트를 feature routes 파일로 분리 (패치 생성 중심)
"""
import argparse, sys, difflib, re, json
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).resolve().parents[1]
APP_ROUTER = ROOT/"lib/app/router/router.dart"   # 필요시 경로 조정
PATCHES = ROOT/"patches"; REPORTS = ROOT/"reports"
for d in (PATCHES, REPORTS): d.mkdir(exist_ok=True)

def gen_feature_routes(feature):
    return f"""// GENERATED by RouterSplitter
import 'package:go_router/go_router.dart';
// TODO: import your feature screens here

final List<RouteBase> {feature}Routes = <RouteBase>[
  // GoRoute(path: '/{feature}', builder: (_, __) => const {feature.capitalize()}Screen()),
];
"""

def wire_in_app_router(text, features):
    begin = "// <ROUTER_SPLITTER BEGIN>"
    end = "// <ROUTER_SPLITTER END>"
    if begin not in text or end not in text:
        text += f"\n{begin}\n// routes will be composed here\n{end}\n"
    block = f"final routes = [\n" + "".join([f"  ...{f}Routes,\n" for f in features]) + "];\n"
    return re.sub(f"{re.escape(begin)}.*?{re.escape(end)}",
                  f"{begin}\n{block}{end}", text, flags=re.S)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--scope", default="all")
    ap.add_argument("--mode", choices=["detect","apply"], default="detect")
    ap.add_argument("--features", default="")
    ap.add_argument("--output", choices=["file", "stdout", "both"], default="file",
                    help="Output destination: file (default), stdout, or both")
    args = ap.parse_args()
    feats = [f.strip() for f in args.features.split(",") if f.strip()]
    if not feats: feats = ["auth","posts","chat","profile","search","notifications"]

    # 1) create per-feature routes files (patch form)
    changes = []
    for f in feats:
        dst = ROOT/f"lib/features/{f}/presentation/routes/{f}_routes.dart"
        new_text = gen_feature_routes(f)
        if dst.exists():
            continue
        changes.append((dst, "", new_text))

    # 2) wire app/router.dart composition
    src = APP_ROUTER.read_text(encoding="utf-8") if APP_ROUTER.exists() else ""
    new_src = wire_in_app_router(src, feats)
    changes.append((APP_ROUTER, src, new_src))

    # write diff
    diff_lines=[]
    for path, old, new in changes:
        a = old.splitlines(True); b = new.splitlines(True)
        rel = str(path.relative_to(ROOT))
        diff_lines += list(difflib.unified_diff(a,b,fromfile=f"a/{rel}",tofile=f"b/{rel}",lineterm=""))
    patch = PATCHES/"router_split_all.diff"
    patch.write_text("\n".join(diff_lines), encoding="utf-8")

    if args.mode=="apply":
        for path, old, new in changes:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(new, encoding="utf-8")

    # Claude-centric JSON output
    routes_split = len(changes) - 1  # Exclude app/router.dart wire-up

    next_action = None
    if routes_split > 0:
        if args.mode == "detect":
            next_action = {
                "recommended_agent": "router-splitter",
                "params": {"mode": "apply", "features": ",".join(feats)},
                "priority": "medium",
                "reason": f"Apply router split for {routes_split} features"
            }
        else:
            next_action = {
                "recommended_agent": "build-sentinel",
                "params": {"mode": "quick"},
                "priority": "medium",
                "reason": f"Verify routing after splitting {routes_split} routes"
            }

    claude_output = {
        "agent": "router-splitter",
        "version": "1.0.0",
        "timestamp": datetime.now().isoformat(),
        "status": "success" if routes_split > 0 else "no_action",
        "data": {
            "mode": args.mode,
            "features": feats,
            "routes_split": routes_split,
            "patch_file": str(patch) if routes_split > 0 else None,
            "changes": len(changes),
            "router_wired": len(changes) > 0,
            "files_created": [
                f"lib/features/{f}/presentation/routes/{f}_routes.dart"
                for f in feats
            ] if args.mode == "apply" else []
        },
        "next_action": next_action,
        "decision_hints": {
            "needs_split": routes_split > 0,
            "ready_to_apply": args.mode == "detect" and routes_split > 0,
            "applied_successfully": args.mode == "apply" and routes_split > 0,
            "router_centralized": APP_ROUTER.exists()
        }
    }

    # Save or output Claude-centric JSON based on args
    json_output = json.dumps(claude_output, ensure_ascii=False, indent=2)

    if args.output in ["file", "both"]:
        (REPORTS / "router_splitter.json").write_text(
            json_output,
            encoding="utf-8"
        )

    if args.output in ["stdout", "both"]:
        print(json_output)
        sys.stdout.flush()

    # Keep legacy output
    (REPORTS / "router_splitter_all.yml").write_text(
        f"features: {feats}\npatch: {patch}\nmode: {args.mode}\n", encoding="utf-8")
    print(f"[RouterSplitter] patch -> {patch} (mode={args.mode})")

if __name__=="__main__":
    sys.exit(main())
