#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
RouterSplitter - app/router.dart 비대 라우트를 feature routes 파일로 분리 (패치 생성 중심)
"""
import argparse, sys, difflib, re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
APP_ROUTER = ROOT/"lib/app/router/router.dart"   # 필요시 경로 조정
PATCHES = ROOT/"patches"; REPORTS = ROOT/"reports"
for d in (PATCHES, REPORTS): d.mkdir(exist_ok=True)

def gen_feature_routes(feature):
    return f"""// GENERATED by RouterSplitter
import 'package:go_router/go_router.dart';
// TODO: import your feature screens here

final List<RouteBase> {feature}Routes = <RouteBase>[
  // GoRoute(path: '/{feature}', builder: (_, __) => const {feature.capitalize()}Screen()),
];
"""

def wire_in_app_router(text, features):
    begin = "// <ROUTER_SPLITTER BEGIN>"
    end = "// <ROUTER_SPLITTER END>"
    if begin not in text or end not in text:
        text += f"\n{begin}\n// routes will be composed here\n{end}\n"
    block = f"final routes = [\n" + "".join([f"  ...{f}Routes,\n" for f in features]) + "];\n"
    return re.sub(f"{re.escape(begin)}.*?{re.escape(end)}",
                  f"{begin}\n{block}{end}", text, flags=re.S)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--scope", default="all")
    ap.add_argument("--mode", choices=["detect","apply"], default="detect")
    ap.add_argument("--features", default="")
    args = ap.parse_args()
    feats = [f.strip() for f in args.features.split(",") if f.strip()]
    if not feats: feats = ["auth","posts","chat","profile","search","notifications"]

    # 1) create per-feature routes files (patch form)
    changes = []
    for f in feats:
        dst = ROOT/f"lib/features/{f}/presentation/routes/{f}_routes.dart"
        new_text = gen_feature_routes(f)
        if dst.exists():
            continue
        changes.append((dst, "", new_text))

    # 2) wire app/router.dart composition
    src = APP_ROUTER.read_text(encoding="utf-8") if APP_ROUTER.exists() else ""
    new_src = wire_in_app_router(src, feats)
    changes.append((APP_ROUTER, src, new_src))

    # write diff
    diff_lines=[]
    for path, old, new in changes:
        a = old.splitlines(True); b = new.splitlines(True)
        rel = str(path.relative_to(ROOT))
        diff_lines += list(difflib.unified_diff(a,b,fromfile=f"a/{rel}",tofile=f"b/{rel}",lineterm=""))
    patch = PATCHES/"router_split_all.diff"
    patch.write_text("\n".join(diff_lines), encoding="utf-8")

    if args.mode=="apply":
        for path, old, new in changes:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(new, encoding="utf-8")

    REPORTS/"router_splitter_all.yml".write_text(
        f"features: {feats}\npatch: {patch}\nmode: {args.mode}\n", encoding="utf-8")
    print(f"[RouterSplitter] patch -> {patch} (mode={args.mode})")

if __name__=="__main__":
    sys.exit(main())
