#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
StructWeaver - (task=mapper|state) 분해/생성 패치
- mapper: 전역 model_adapter → features/*/data/mappers/* 생성 스텁
- state:   app_state 등 전역 상태 → features/*/presentation/providers/* 생성 스텁
기능: detect(패치 생성), apply(파일 생성)
"""
import argparse, sys, difflib, json
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).resolve().parents[1]
PATCHES = ROOT/"patches"; REPORTS = ROOT/"reports"
for d in (PATCHES, REPORTS): d.mkdir(exist_ok=True)

def mk_diff(changes):
    diff=[]
    for path, old, new in changes:
        a=old.splitlines(True); b=new.splitlines(True)
        rel=str(path.relative_to(ROOT))
        diff += list(difflib.unified_diff(a,b,fromfile=f"a/{rel}",tofile=f"b/{rel}",lineterm=""))
    return "\n".join(diff)

def mapper_stub(feature, entity):
    return f"""// GENERATED by StructWeaver @ {datetime.utcnow().isoformat()}Z
// TODO: implement DTO and mapping for {entity}
class {entity}Dto {{}}
class {entity}Mapper {{
  static {entity}Dto toDto(/* {entity} */ src) => {entity}Dto();
  static /* {entity} */ fromDto({entity}Dto dto) => throw UnimplementedError();
}}
"""

def provider_stub(feature, name):
    return f"""// GENERATED by StructWeaver @ {datetime.utcnow().isoformat()}Z
import 'package:flutter/foundation.dart';
class {name} extends ChangeNotifier {{
  // TODO: move state & actions here
}}
"""

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--task", choices=["mapper","state"], required=True)
    ap.add_argument("--source", default="lib/backend/models/migration/model_adapter.dart")
    ap.add_argument("--file", default="lib/app/state/app_state.dart")
    ap.add_argument("--features", default="auto")
    ap.add_argument("--map", default="")  # "SymA->lib/features/upload/presentation/providers/upload_provider.dart;SymB->..."
    ap.add_argument("--mode", choices=["detect","apply"], default="detect")
    ap.add_argument("--output", choices=["file", "stdout", "both"], default="file",
                    help="Output destination: file (default), stdout, or both")
    args = ap.parse_args()

    changes=[]
    if args.task=="mapper":
        # 초간단: posts/profile 예시 스텁 생성
        targets = [
            (ROOT/"lib/features/profile/data/mappers/user_mapper.dart", mapper_stub("profile","User")),
            (ROOT/"lib/features/posts/data/mappers/post_mapper.dart", mapper_stub("posts","Post")),
        ]
        for p, content in targets:
            old = p.read_text(encoding="utf-8") if p.exists() else ""
            changes.append((p, old, content))
        patch = PATCHES/"struct_weaver_mapper.diff"
    else:
        # state 분해: map 파라미터 기준 스텁 생성
        pairs = [s.strip() for s in args.map.split(";") if s.strip()]
        for pair in pairs:
            if "->" not in pair: continue
            sym, dst = [x.strip() for x in pair.split("->",1)]
            content = provider_stub("feature", sym)
            p = ROOT/dst
            old = p.read_text(encoding="utf-8") if p.exists() else ""
            changes.append((p, old, content))
        patch = PATCHES/"struct_weaver_state.diff"

    diff = mk_diff(changes)
    patch.write_text(diff, encoding="utf-8")

    if args.mode=="apply":
        for p, old, new in changes:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(new, encoding="utf-8")

    # Claude-centric JSON output
    structures_decomposed = len(changes)

    next_action = None
    if structures_decomposed > 0:
        if args.mode == "detect":
            next_action = {
                "recommended_agent": "struct-weaver",
                "params": {"task": args.task, "mode": "apply"},
                "priority": "medium",
                "reason": f"Apply patches for {structures_decomposed} structures"
            }
        else:
            next_action = {
                "recommended_agent": "import-guardian",
                "params": {"mode": "detect", "scope": "all"},
                "priority": "high",
                "reason": f"Check imports after decomposing {structures_decomposed} structures"
            }

    # Extract affected features for decision hints
    affected_features = set()
    for p, _, _ in changes:
        path_str = str(p)
        if "/features/" in path_str:
            feature = path_str.split("/features/")[1].split("/")[0]
            affected_features.add(feature)

    claude_output = {
        "agent": "struct-weaver",
        "version": "1.0.0",
        "timestamp": datetime.now().isoformat(),
        "status": "success" if structures_decomposed > 0 else "no_action",
        "data": {
            "task": args.task,
            "mode": args.mode,
            "structures_decomposed": structures_decomposed,
            "patch_file": str(patch) if structures_decomposed > 0 else None,
            "affected_features": list(affected_features),
            "files_created": [
                str(p.relative_to(ROOT)) for p, _, _ in changes
            ] if args.mode == "apply" else [],
            "source_file": args.source if args.task == "mapper" else args.file
        },
        "next_action": next_action,
        "decision_hints": {
            "needs_decomposition": structures_decomposed > 0,
            "ready_to_apply": args.mode == "detect" and structures_decomposed > 0,
            "applied_successfully": args.mode == "apply" and structures_decomposed > 0,
            "task_type": args.task,
            "features_affected": len(affected_features)
        }
    }

    # Save or output Claude-centric JSON based on args
    json_output = json.dumps(claude_output, ensure_ascii=False, indent=2)

    if args.output in ["file", "both"]:
        (REPORTS / "struct_weaver.json").write_text(
            json_output,
            encoding="utf-8"
        )

    if args.output in ["stdout", "both"]:
        print(json_output)
        sys.stdout.flush()

    # Keep legacy output
    (REPORTS / f"struct_weaver_{args.task}.yml").write_text(
        f"task: {args.task}\nmode: {args.mode}\npatch: {patch}\nfiles: {len(changes)}\n",
        encoding="utf-8"
    )
    print(f"[StructWeaver] patch -> {patch} (mode={args.mode})")

if __name__=="__main__":
    sys.exit(main())
