#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
StructWeaver - (task=mapper|state) 분해/생성 패치
- mapper: 전역 model_adapter → features/*/data/mappers/* 생성 스텁
- state:   app_state 등 전역 상태 → features/*/presentation/providers/* 생성 스텁
기능: detect(패치 생성), apply(파일 생성)
"""
import argparse, sys, difflib
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).resolve().parents[1]
PATCHES = ROOT/"patches"; REPORTS = ROOT/"reports"
for d in (PATCHES, REPORTS): d.mkdir(exist_ok=True)

def mk_diff(changes):
    diff=[]
    for path, old, new in changes:
        a=old.splitlines(True); b=new.splitlines(True)
        rel=str(path.relative_to(ROOT))
        diff += list(difflib.unified_diff(a,b,fromfile=f"a/{rel}",tofile=f"b/{rel}",lineterm=""))
    return "\n".join(diff)

def mapper_stub(feature, entity):
    return f"""// GENERATED by StructWeaver @ {datetime.utcnow().isoformat()}Z
// TODO: implement DTO and mapping for {entity}
class {entity}Dto {{}}
class {entity}Mapper {{
  static {entity}Dto toDto(/* {entity} */ src) => {entity}Dto();
  static /* {entity} */ fromDto({entity}Dto dto) => throw UnimplementedError();
}}
"""

def provider_stub(feature, name):
    return f"""// GENERATED by StructWeaver @ {datetime.utcnow().isoformat()}Z
import 'package:flutter/foundation.dart';
class {name} extends ChangeNotifier {{
  // TODO: move state & actions here
}}
"""

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--task", choices=["mapper","state"], required=True)
    ap.add_argument("--source", default="lib/backend/models/migration/model_adapter.dart")
    ap.add_argument("--file", default="lib/app/state/app_state.dart")
    ap.add_argument("--features", default="auto")
    ap.add_argument("--map", default="")  # "SymA->lib/features/upload/presentation/providers/upload_provider.dart;SymB->..."
    ap.add_argument("--mode", choices=["detect","apply"], default="detect")
    args = ap.parse_args()

    changes=[]
    if args.task=="mapper":
        # 초간단: posts/profile 예시 스텁 생성
        targets = [
            (ROOT/"lib/features/profile/data/mappers/user_mapper.dart", mapper_stub("profile","User")),
            (ROOT/"lib/features/posts/data/mappers/post_mapper.dart", mapper_stub("posts","Post")),
        ]
        for p, content in targets:
            old = p.read_text(encoding="utf-8") if p.exists() else ""
            changes.append((p, old, content))
        patch = PATCHES/"struct_weaver_mapper.diff"
    else:
        # state 분해: map 파라미터 기준 스텁 생성
        pairs = [s.strip() for s in args.map.split(";") if s.strip()]
        for pair in pairs:
            if "->" not in pair: continue
            sym, dst = [x.strip() for x in pair.split("->",1)]
            content = provider_stub("feature", sym)
            p = ROOT/dst
            old = p.read_text(encoding="utf-8") if p.exists() else ""
            changes.append((p, old, content))
        patch = PATCHES/"struct_weaver_state.diff"

    diff = mk_diff(changes)
    patch.write_text(diff, encoding="utf-8")
    REPORTS/f"struct_weaver_{args.task}.yml".write_text(
        f"task: {args.task}\nmode: {args.mode}\npatch: {patch}\nfiles: {len(changes)}\n",
        encoding="utf-8"
    )
    if args.mode=="apply":
        for p, old, new in changes:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(new, encoding="utf-8")
    print(f"[StructWeaver] patch -> {patch} (mode={args.mode})")

if __name__=="__main__":
    sys.exit(main())
