// Email Verification UseCase
// Clean Architecture - Domain Layer

import 'package:dartz/dartz.dart';
import 'package:flutter/foundation.dart';
import '/core/utils/idempotency_service.dart';
import '../repositories/i_auth_repository.dart';
import '../failures/auth_failure.dart';

/// EmailVerificationUseCase
///
/// Comprehensive email verification that handles:
/// - Sending verification emails
/// - Checking verification status
/// - Resending verification emails with spam prevention
///
/// **Clean Architecture v4.0 - Either Pattern + IdempotencyService**:
/// - Returns Either<AuthFailure, T> for functional error handling
/// - IdempotencyService integration for spam prevention
/// - Consistent with Voting feature architecture
class EmailVerificationUseCase {
  final IAuthRepository _repository;
  final IdempotencyService _idempotencyService;

  // Rate limiting for additional protection (backup to IdempotencyService)
  DateTime? _lastVerificationSentTime;
  static const Duration _resendDelay = Duration(minutes: 1);

  EmailVerificationUseCase({
    required IAuthRepository repository,
    required IdempotencyService idempotencyService,
  })  : _repository = repository,
        _idempotencyService = idempotencyService;

  /// Send Verification Email with Idempotency
  ///
  /// Uses IdempotencyService to prevent spam:
  /// - First execution: Sends email and stores eventId
  /// - Network retry (same eventId): Skips operation safely
  /// - Spam attempt (different eventId): Returns success without sending (already sent)
  ///
  /// [userId] - Current user ID for idempotency tracking
  /// [eventId] - UUID v4 generated by client for idempotency check
  Future<Either<AuthFailure, Unit>> sendVerificationEmail({
    required String userId,
    required String eventId,
  }) async {
    try {
      debugPrint('Sending email verification (userId: $userId, eventId: $eventId)...');

      // Check if user is signed in
      final currentUser = await _repository.getCurrentUser();
      if (currentUser == null) {
        debugPrint('No user signed in');
        return left(const AuthFailure.userNotFound());
      }

      // Check if already verified
      if (currentUser.isEmailVerified) {
        debugPrint('Email already verified');
        return right(unit);
      }

      // Check rate limiting (additional protection)
      if (!_canSendVerification()) {
        debugPrint('Rate limit check: Please wait before sending another verification email');
        return left(AuthFailure.unexpected('잠시 후 다시 시도해주세요'));
      }

      // Execute with IdempotencyService
      await _idempotencyService.executeIdempotent<Unit>(
        entityType: 'auth_email_verify',
        entityId: userId,
        userId: userId,
        eventId: eventId,
        operation: (transaction) async {
          debugPrint('Idempotency check passed, sending verification email...');

          // Send verification email
          final success = await _repository.sendEmailVerification();

          if (!success) {
            debugPrint('Failed to send verification email');
            throw const AuthFailure.serverError();
          }

          _lastVerificationSentTime = DateTime.now();
          debugPrint('Verification email sent successfully');
          return unit;
        },
      );

      return right(unit);

    } on IdempotencyViolation catch (e) {
      // Already sent - treat as success to avoid spamming user
      debugPrint('Verification email already sent (spam prevention): $e');
      return right(unit);
    } on AuthFailure catch (e) {
      debugPrint('Send verification failed with AuthFailure: ${e.message}');
      return left(e);
    } catch (e) {
      debugPrint('Send verification failed with unexpected error: $e');
      return left(AuthFailure.unexpected(e.toString()));
    }
  }

  /// Resend Verification Email with Idempotency
  ///
  /// Resends verification email with rate limiting
  ///
  /// [userId] - Current user ID for idempotency tracking
  /// [eventId] - UUID v4 generated by client for idempotency check
  Future<Either<AuthFailure, Unit>> resendVerificationEmail({
    required String userId,
    required String eventId,
  }) async {
    debugPrint('Attempting to resend verification email...');

    if (_lastVerificationSentTime != null) {
      final timeSinceLastSend = DateTime.now().difference(_lastVerificationSentTime!);
      if (timeSinceLastSend < _resendDelay) {
        final secondsLeft = (_resendDelay - timeSinceLastSend).inSeconds;
        debugPrint('Please wait $secondsLeft seconds before resending');
        return left(AuthFailure.unexpected('$secondsLeft초 후에 다시 시도해주세요'));
      }
    }

    return sendVerificationEmail(userId: userId, eventId: eventId);
  }

  /// Check Email Verification Status
  ///
  /// Returns true if email is verified, false otherwise
  Future<bool> isEmailVerified() async {
    try {
      // Get current user
      final currentUser = await _repository.getCurrentUser();
      if (currentUser == null) {
        debugPrint('No user signed in');
        return false;
      }

      // Check verification status
      final isVerified = currentUser.isEmailVerified;

      debugPrint('Email verification status: $isVerified');
      return isVerified;

    } on AuthFailure catch (e) {
      debugPrint('Check verification failed with AuthFailure: ${e.message}');
      return false;
    } catch (e) {
      debugPrint('Check verification failed with unexpected error: $e');
      return false;
    }
  }

  /// Get Current User Email
  ///
  /// Returns the email of the current user
  Future<String?> getCurrentUserEmail() async {
    try {
      final currentUser = await _repository.getCurrentUser();
      return currentUser?.email;
    } catch (e) {
      debugPrint('Failed to get user email: $e');
      return null;
    }
  }

  /// Check if verification can be sent (rate limiting)
  bool _canSendVerification() {
    if (_lastVerificationSentTime == null) {
      return true;
    }

    final timeSinceLastSend = DateTime.now().difference(_lastVerificationSentTime!);
    return timeSinceLastSend >= _resendDelay;
  }

  /// Reset verification timer
  void resetVerificationTimer() {
    _lastVerificationSentTime = null;
  }

  /// Get seconds until next verification can be sent
  int getSecondsUntilResend() {
    if (_lastVerificationSentTime == null) {
      return 0;
    }

    final timeSinceLastSend = DateTime.now().difference(_lastVerificationSentTime!);
    if (timeSinceLastSend >= _resendDelay) {
      return 0;
    }

    return (_resendDelay - timeSinceLastSend).inSeconds;
  }
}
