// Password Management UseCase
// Clean Architecture - Domain Layer

import 'package:flutter/foundation.dart';
import '/core/utils/idempotency_service.dart';
import '../repositories/i_auth_repository.dart';
import '../failures/auth_failure.dart';

/// PasswordManagementUseCase
///
/// Comprehensive password management that handles:
/// - Password reset via email with spam prevention
/// - Password updates for authenticated users
/// - Password strength validation
///
/// **Clean Architecture v4.0 + IdempotencyService**:
/// - IdempotencyService integration for attack prevention
/// - Consistent with Voting feature architecture
class PasswordManagementUseCase {
  final IAuthRepository _repository;
  final IdempotencyService _idempotencyService;

  PasswordManagementUseCase({
    required IAuthRepository repository,
    required IdempotencyService idempotencyService,
  })  : _repository = repository,
        _idempotencyService = idempotencyService;

  /// Send Password Reset Email with Idempotency
  ///
  /// Uses IdempotencyService to prevent spam attacks:
  /// - First execution: Sends email and stores eventId
  /// - Network retry (same eventId): Skips operation safely
  /// - Attack attempt (different eventId): Returns success without sending (already sent)
  ///
  /// [email] - Email address to send password reset to
  /// [eventId] - UUID v4 generated by client for idempotency check
  Future<bool> sendPasswordResetEmail({
    required String email,
    required String eventId,
  }) async {
    try {
      debugPrint('Sending password reset email to: $email (eventId: $eventId)');

      // Validate email format
      if (!_isValidEmail(email)) {
        debugPrint('Invalid email format: $email');
        return false;
      }

      // Execute with IdempotencyService
      await _idempotencyService.executeIdempotent<void>(
        entityType: 'auth_password_reset',
        entityId: email,
        userId: email,
        eventId: eventId,
        operation: (transaction) async {
          debugPrint('Idempotency check passed, sending password reset email...');

          // Send reset email
          await _repository.sendPasswordResetEmail(email);

          debugPrint('Password reset email sent successfully');
        },
      );

      return true;

    } on IdempotencyViolation catch (e) {
      // Already sent - treat as success to prevent attack feedback
      debugPrint('Password reset email already sent (attack prevention): $e');
      return true;
    } on AuthFailure catch (e) {
      debugPrint('Password reset failed with AuthFailure: ${e.message}');
      return false;
    } catch (e) {
      debugPrint('Password reset failed with unexpected error: $e');
      return false;
    }
  }

  /// Update Password
  ///
  /// Updates the password for the currently authenticated user
  Future<bool> updatePassword({
    required String currentPassword,
    required String newPassword,
  }) async {
    try {
      debugPrint('Updating user password...');

      // Validate new password strength
      if (!_isValidPassword(newPassword)) {
        debugPrint('New password does not meet requirements');
        return false;
      }

      // Verify passwords are different
      if (currentPassword == newPassword) {
        debugPrint('New password must be different from current password');
        return false;
      }

      // Check if user is authenticated
      if (!_repository.isSignedIn) {
        debugPrint('User must be authenticated to update password');
        return false;
      }

      // Re-authenticate with current password first
      final currentUser = await _repository.getCurrentUser();
      if (currentUser == null || currentUser.email == null) {
        debugPrint('Could not get current user details');
        return false;
      }

      // Re-authenticate to verify current password
      final reAuthUser = await _repository.signInWithEmailAndPassword(
        currentUser.email!,
        currentPassword,
      );

      if (reAuthUser == null) {
        debugPrint('Current password is incorrect');
        return false;
      }

      // Update to new password using the repository method
      final success = await _repository.updatePassword(newPassword);

      if (success) {
        debugPrint('Password updated successfully');
      } else {
        debugPrint('Password update failed');
      }

      return success;

    } on AuthFailure catch (e) {
      debugPrint('Password update failed with AuthFailure: ${e.message}');

      // Re-throw specific errors for UI handling
      if (e is RequiresRecentLogin) {
        rethrow;
      }
      return false;
    } catch (e) {
      debugPrint('Password update failed with unexpected error: $e');
      return false;
    }
  }

  /// Reset Password (Backward compatibility)
  ///
  /// Alias for sendPasswordResetEmail
  ///
  /// [email] - Email address to send password reset to
  /// [eventId] - UUID v4 generated by client for idempotency check
  Future<bool> resetPassword({
    required String email,
    required String eventId,
  }) async {
    return sendPasswordResetEmail(email: email, eventId: eventId);
  }

  /// Validate email format
  bool _isValidEmail(String email) {
    final emailRegex = RegExp(
      r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$',
    );
    return emailRegex.hasMatch(email);
  }

  /// Validate password strength
  bool _isValidPassword(String password) {
    // Minimum 6 characters (Firebase requirement)
    if (password.length < 6) {
      return false;
    }

    // Additional requirements could be added:
    // - Contains uppercase letter
    // - Contains lowercase letter
    // - Contains number
    // - Contains special character

    return true;
  }

  /// Check password strength
  ///
  /// Returns a score from 0 to 100 indicating password strength
  int getPasswordStrength(String password) {
    int score = 0;

    // Length scoring
    if (password.length >= 6) score += 20;
    if (password.length >= 8) score += 20;
    if (password.length >= 12) score += 20;

    // Character variety scoring
    if (RegExp(r'[a-z]').hasMatch(password)) score += 10;
    if (RegExp(r'[A-Z]').hasMatch(password)) score += 10;
    if (RegExp(r'[0-9]').hasMatch(password)) score += 10;
    if (RegExp(r'[!@#$%^&*(),.?":{}|<>]').hasMatch(password)) score += 10;

    return score.clamp(0, 100);
  }
}
