// Sign Up With Email UseCase
// Clean Architecture - Domain Layer

import 'package:dartz/dartz.dart';
import 'package:flutter/foundation.dart';
import '/core/utils/idempotency_service.dart';
import '../entities/auth_user.dart';
import '../repositories/i_auth_repository.dart';
import '../failures/auth_failure.dart';

/// SignUpWithEmailUseCase
///
/// Handles email/password account creation.
/// This is separate from SignInWithEmailUseCase to maintain
/// single responsibility principle.
///
/// **Clean Architecture v4.0 - Either Pattern + IdempotencyService**:
/// - Returns Either<AuthFailure, AuthUser> for functional error handling
/// - Type-safe error handling with AuthFailure sealed class
/// - IdempotencyService integration for duplicate prevention
/// - Consistent with Voting feature architecture
class SignUpWithEmailUseCase {
  final IAuthRepository _repository;
  final IdempotencyService _idempotencyService;

  SignUpWithEmailUseCase({
    required IAuthRepository repository,
    required IdempotencyService idempotencyService,
  })  : _repository = repository,
        _idempotencyService = idempotencyService;

  /// Execute Email Sign Up with Idempotency
  ///
  /// Creates a new user account with email and password.
  /// Uses IdempotencyService to prevent duplicate signups:
  /// - First execution: Creates account and stores eventId
  /// - Network retry (same eventId): Skips operation safely
  /// - Real duplicate (different eventId): Throws IdempotencyViolation
  ///
  /// [eventId] - UUID v4 generated by client for idempotency check
  Future<Either<AuthFailure, AuthUser>> execute({
    required String email,
    required String password,
    required String eventId,
    String? displayName,
  }) async {
    try {
      debugPrint('Creating account with email (eventId: $eventId)...');

      // Validate email format
      if (!_isValidEmail(email)) {
        debugPrint('Invalid email format: $email');
        return left(const AuthFailure.invalidEmail());
      }

      // Validate password strength
      if (!_isValidPassword(password)) {
        debugPrint('Password does not meet requirements');
        return left(const AuthFailure.weakPassword());
      }

      // Execute with IdempotencyService
      final user = await _idempotencyService.executeIdempotent<AuthUser>(
        entityType: 'auth_signup',
        entityId: email,
        userId: email,
        eventId: eventId,
        operation: (transaction) async {
          debugPrint('Idempotency check passed, creating account...');

          // Create user account
          final user = await _repository.createUserWithEmailAndPassword(
            email,
            password,
          );

          if (user == null) {
            debugPrint('Account creation failed');
            throw const AuthFailure.emailAlreadyInUse();
          }

          // Update display name if provided
          if (displayName != null && displayName.isNotEmpty) {
            await _repository.updateUserProfile(
              displayName: displayName,
            );
          }

          // Send email verification
          await _repository.sendEmailVerification();

          debugPrint('Account created successfully: ${user.uid}');
          return user;
        },
      );

      return right(user);

    } on IdempotencyViolation catch (e) {
      debugPrint('Account creation blocked - duplicate attempt: $e');
      return left(const AuthFailure.emailAlreadyInUse());
    } on AuthFailure catch (e) {
      debugPrint('Account creation failed with AuthFailure: ${e.message}');
      return left(e);
    } catch (e) {
      debugPrint('Account creation failed with unexpected error: $e');
      return left(AuthFailure.unexpected(e.toString()));
    }
  }

  /// Validate email format
  bool _isValidEmail(String email) {
    // Basic email validation
    final emailRegex = RegExp(
      r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$',
    );
    return emailRegex.hasMatch(email);
  }

  /// Validate password strength
  bool _isValidPassword(String password) {
    // Minimum 6 characters (Firebase requirement)
    if (password.length < 6) {
      return false;
    }

    // Could add more requirements here:
    // - Contains uppercase letter
    // - Contains lowercase letter
    // - Contains number
    // - Contains special character

    return true;
  }
}
