// Mocks generated by Mockito 5.4.6 from annotations
// in versus_space/test/features/notifications/data/repositories/notification_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:versus_space/services/batch/batch_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BatchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBatchService extends _i1.Mock implements _i2.BatchService {
  MockBatchService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> executeBatch({
    required List<_i2.BatchOperation>? operations,
    void Function(int, int)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#executeBatch, [], {
              #operations: operations,
              #onProgress: onProgress,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateFullProfile({
    required String? userId,
    required Map<String, dynamic>? profileData,
    Map<String, dynamic>? settingsData,
    List<String>? interests,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateFullProfile, [], {
              #userId: userId,
              #profileData: profileData,
              #settingsData: settingsData,
              #interests: interests,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteUserAccount({
    required String? userId,
    required List<String>? chatIds,
    required List<String>? postIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserAccount, [], {
              #userId: userId,
              #chatIds: chatIds,
              #postIds: postIds,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> createBulkNotifications({
    required List<Map<String, dynamic>>? notifications,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBulkNotifications, [], {
              #notifications: notifications,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> submitVoteWithCounters({
    required String? postId,
    required String? userId,
    required String? voteOption,
    required int? currentCounterA,
    required int? currentCounterB,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitVoteWithCounters, [], {
              #postId: postId,
              #userId: userId,
              #voteOption: voteOption,
              #currentCounterA: currentCounterA,
              #currentCounterB: currentCounterB,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
